import { draftChapter } from "./draft";

/** Checks use positive powers only (2⁻³ is checked as 1/2³) because the algebra engine reads whole-number exponents. */
export const EXPONENTS_POWERS = draftChapter("exponents-powers", 10, [
  ["EP_POWER_MEANING", "What a power means", 0, [], ["MULTIPLIED_BASE_BY_EXPONENT"]],
  ["EP_NEGATIVE_EXP", "Negative exponents", 1, ["EP_POWER_MEANING"], ["NEGATIVE_EXPONENT_NEGATIVE_NUMBER"]],
  ["EP_PRODUCT_LAW", "aᵐ × aⁿ = aᵐ⁺ⁿ", 1, ["EP_POWER_MEANING"], ["MULTIPLIED_EXPONENTS", "MULTIPLIED_BASES"]],
  ["EP_QUOTIENT_LAW", "aᵐ ÷ aⁿ = aᵐ⁻ⁿ", 1, ["EP_POWER_MEANING"], ["DIVIDED_EXPONENTS"]],
  ["EP_NEG_BASE", "Powers of negative numbers", 1, ["EP_POWER_MEANING"], ["SIGN_OF_EVEN_POWER"]],
  ["EP_ZERO_EXP", "a⁰ = 1", 1, ["EP_QUOTIENT_LAW"], ["ZERO_POWER_IS_ZERO"]],
  ["EP_POWER_LAW", "(aᵐ)ⁿ = aᵐⁿ", 2, ["EP_PRODUCT_LAW"], ["ADDED_EXPONENTS"]],
  ["EP_SAME_EXP", "aᵐ × bᵐ = (ab)ᵐ", 2, ["EP_PRODUCT_LAW"], ["ADDED_BASES"]],
  ["EP_FRACTION_POWER", "Powers of fractions", 2, ["EP_NEGATIVE_EXP"], ["POWERED_ONE_PART"]],
  ["EP_NEG_FRACTION", "Negative powers of fractions", 3, ["EP_FRACTION_POWER"], ["FRACTION_NOT_FLIPPED"]],
  ["EP_STANDARD_FORM", "Standard form", 3, ["EP_NEGATIVE_EXP"], ["POWER_SIGN_WRONG", "COEFFICIENT_OUT_OF_RANGE"]],
  ["EP_LAWS_COMBINED", "Simplifying with several laws", 4, ["EP_POWER_LAW", "EP_QUOTIENT_LAW", "EP_NEGATIVE_EXP"], ["LAWS_MIXED_UP"]],
  ["EP_STANDARD_COMPARE", "Comparing and multiplying in standard form", 4, ["EP_STANDARD_FORM"], ["COMPARED_COEFFICIENTS_ONLY", "POWERS_OF_TEN_MULTIPLIED"]],
  ["EP_SOLVE_EXP", "Finding an unknown exponent", 4, ["EP_PRODUCT_LAW"], ["EXPONENTS_NOT_EQUATED"]],
], {
  MULTIPLIED_BASE_BY_EXPONENT: "Works out 3⁴ as 3 × 4.",
  NEGATIVE_EXPONENT_NEGATIVE_NUMBER: "Thinks 2⁻³ is −8.",
  MULTIPLIED_EXPONENTS: "Multiplies the exponents when multiplying powers.",
  MULTIPLIED_BASES: "Multiplies the bases as well as adding the exponents.",
  DIVIDED_EXPONENTS: "Divides the exponents when dividing powers.",
  SIGN_OF_EVEN_POWER: "Gets the sign of a negative number's power wrong.",
  ZERO_POWER_IS_ZERO: "Thinks anything to the power 0 is 0.",
  ADDED_EXPONENTS: "Adds the exponents for a power of a power.",
  ADDED_BASES: "Adds the bases (2⁵ × 5⁵ = 7⁵ or 7¹⁰).",
  POWERED_ONE_PART: "Raises only the top or only the bottom of a fraction to the power.",
  FRACTION_NOT_FLIPPED: "Doesn't flip the fraction for a negative power.",
  POWER_SIGN_WRONG: "Uses a positive power of 10 for a small number, or the reverse.",
  COEFFICIENT_OUT_OF_RANGE: "Leaves the number in front outside 1 to 10.",
  LAWS_MIXED_UP: "Uses the wrong law partway through.",
  COMPARED_COEFFICIENTS_ONLY: "Compares the numbers in front and ignores the powers of 10.",
  POWERS_OF_TEN_MULTIPLIED: "Multiplies the powers of 10's exponents instead of adding them.",
  EXPONENTS_NOT_EQUATED: "Doesn't set the exponents equal once the bases match.",
}, [
  ["EP_POWER_MEANING", "NUMBER", "easy", "EXPLORE", "What is 3⁴?", "81", [], ["MULTIPLIED_BASE_BY_EXPONENT"], "3^4"],
  ["EP_NEGATIVE_EXP", "NUMBER", "easy", "EXPLORE", "Write 2⁻³ as a fraction.", "1/8", [], ["NEGATIVE_EXPONENT_NEGATIVE_NUMBER"], "1 / 2^3"],
  ["EP_PRODUCT_LAW", "EXPRESSION", "easy", "EXPLORE", "Simplify a⁵ × a³.", "a^8", [], ["MULTIPLIED_EXPONENTS"], "a^5 * a^3"],
  ["EP_QUOTIENT_LAW", "EXPRESSION", "easy", "EXPLORE", "Simplify x⁹ ÷ x⁴.", "x^5", [], ["DIVIDED_EXPONENTS"], "x^9 / x^4"],
  ["EP_POWER_LAW", "EXPRESSION", "easy", "EXPLORE", "Simplify (y³)⁴.", "y^12", [], ["ADDED_EXPONENTS"], "(y^3)^4"],
  ["EP_ZERO_EXP", "NUMBER", "easy", "EXPLORE", "What is 7⁰ + 5⁰?", "2", [], ["ZERO_POWER_IS_ZERO"], "1 + 1"],
  ["EP_NEG_BASE", "NUMBER", "medium", "EXPLORE", "What is (−2)⁴?", "16", [], ["SIGN_OF_EVEN_POWER"], "(-2)^4"],
  ["EP_FRACTION_POWER", "NUMBER", "easy", "EXPLORE", "What is (2/3)³?", "8/27", [], ["POWERED_ONE_PART"], "(2/3)^3"],
  ["EP_NEG_FRACTION", "NUMBER", "medium", "EXPLORE", "What is (3/4)⁻²?", "16/9", [], ["FRACTION_NOT_FLIPPED"], "(4/3)^2"],
  ["EP_SAME_EXP", "NUMBER", "medium", "EXPLORE", "What is 2⁵ × 5⁵?", "100000", [], ["ADDED_BASES"], "2^5 * 5^5"],
  ["EP_STANDARD_FORM", "CHOICE", "easy", "EXPLORE", "Which is 0.00056 in standard form?", ["5.6 × 10⁻⁴", "5.6 × 10⁴", "56 × 10⁻⁵", "0.56 × 10⁻³"], [], ["POWER_SIGN_WRONG", "COEFFICIENT_OUT_OF_RANGE"]],
  ["EP_STANDARD_FORM", "CHOICE", "medium", "EXPLORE", "Which is 3,40,00,000 in standard form?", ["3.4 × 10⁷", "3.4 × 10⁶", "34 × 10⁶", "3.4 × 10⁻⁷"], [], ["POWER_SIGN_WRONG", "COEFFICIENT_OUT_OF_RANGE"]],
  ["EP_QUOTIENT_LAW", "NUMBER", "medium", "EXPLORE", "Write 5⁶ ÷ 5⁸ as a fraction.", "1/25", ["EP_NEGATIVE_EXP"], ["DIVIDED_EXPONENTS", "NEGATIVE_EXPONENT_NEGATIVE_NUMBER"], "5^6 / 5^8"],

  ["EP_LAWS_COMBINED", "NUMBER", "hard", "DIAGNOSE", "Simplify (2⁵ × 2⁻³) ÷ 2⁴ and write it as a fraction.", "1/4", [], ["LAWS_MIXED_UP"], "2^5 / 2^3 / 2^4"],
  ["EP_NEG_FRACTION", "NUMBER", "hard", "DIAGNOSE", "What is (1/2)⁻² + (1/3)⁻²?", "13", ["EP_NEGATIVE_EXP"], ["FRACTION_NOT_FLIPPED", "NEGATIVE_EXPONENT_NEGATIVE_NUMBER"], "2^2 + 3^2"],
  ["EP_SOLVE_EXP", "NUMBER", "medium", "DIAGNOSE", "Find m if 5ᵐ ÷ 5⁻³ = 5⁵.", "2", ["EP_QUOTIENT_LAW"], ["EXPONENTS_NOT_EQUATED", "DIVIDED_EXPONENTS"], "x + 3 = 5"],
  ["EP_LAWS_COMBINED", "EXPRESSION", "hard", "DIAGNOSE", "Simplify (x²)³ × x⁴ ÷ x⁵.", "x^5", ["EP_POWER_LAW"], ["LAWS_MIXED_UP", "ADDED_EXPONENTS"], "(x^2)^3 * x^4 / x^5"],
  ["EP_STANDARD_COMPARE", "CHOICE", "medium", "DIAGNOSE", "Which is larger: 3 × 10⁻⁵ or 9 × 10⁻⁶?", ["3 × 10⁻⁵", "9 × 10⁻⁶", "They are equal", "You can't tell"], [], ["COMPARED_COEFFICIENTS_ONLY"]],
  ["EP_NEG_BASE", "CHOICE", "medium", "DIAGNOSE", "Which of these is negative?", ["(−3)⁵", "(−3)⁴", "(−3)⁰", "(−3)⁻²"], [], ["SIGN_OF_EVEN_POWER"]],

  ["EP_SOLVE_EXP", "NUMBER", "hard", "CONFIRM", "Find m if (−3)ᵐ⁺¹ × (−3)⁵ = (−3)⁷.", "1", [], ["EXPONENTS_NOT_EQUATED"], "x + 1 + 5 = 7"],
  ["EP_LAWS_COMBINED", "NUMBER", "hard", "CONFIRM", "What is (3⁻¹ + 4⁻¹ + 5⁻¹)⁰?", "1", ["EP_ZERO_EXP"], ["ZERO_POWER_IS_ZERO", "LAWS_MIXED_UP"]],
  ["EP_NEG_FRACTION", "NUMBER", "hard", "CONFIRM", "What is (−2/3)⁻³?", "-27/8", ["EP_NEG_BASE"], ["FRACTION_NOT_FLIPPED", "SIGN_OF_EVEN_POWER"], "(-3/2)^3"],
  ["EP_STANDARD_COMPARE", "CHOICE", "hard", "CONFIRM", "What is (2 × 10³) × (4 × 10⁻⁵) in standard form?", ["8 × 10⁻²", "8 × 10⁻¹⁵", "6 × 10⁻²", "8 × 10²"], [], ["POWERS_OF_TEN_MULTIPLIED"]],
  ["EP_POWER_LAW", "NUMBER", "medium", "CONFIRM", "What is (2³)² ÷ 2⁴?", "4", ["EP_QUOTIENT_LAW"], ["ADDED_EXPONENTS", "DIVIDED_EXPONENTS"], "(2^3)^2 / 2^4"],
  ["EP_STANDARD_FORM", "NUMBER", "medium", "CONFIRM", "Write 4.5 × 10⁻³ as an ordinary number.", "0.0045", [], ["POWER_SIGN_WRONG"], "45/10 / 10^3"],
]);
