import { draftChapter } from "./draft";

/** The closest chapter to what Cogna checks today: every EXPRESSION answer is compared by the existing algebra engine. */
export const ALGEBRAIC_EXPRESSIONS = draftChapter("algebraic-expressions", 8, [
  ["AE_TERMS", "Terms, coefficients and like terms", 0, [], ["COEFFICIENT_SIGN_DROPPED", "UNLIKE_AS_LIKE"]],
  ["AE_EVALUATE", "Substituting values", 1, ["AE_TERMS"], ["SIGN_LOST_ON_SUBSTITUTION", "POWER_OF_NEGATIVE"]],
  ["AE_ADD_SUB", "Adding and subtracting expressions", 1, ["AE_TERMS"], ["COMBINED_UNLIKE_TERMS", "SUBTRACTED_FIRST_TERM_ONLY"]],
  ["AE_MONO_MONO", "Multiplying monomials", 1, ["AE_TERMS"], ["ADDED_COEFFICIENTS", "MULTIPLIED_EXPONENTS"]],
  ["AE_MONO_POLY", "Multiplying a monomial by a polynomial", 2, ["AE_MONO_MONO"], ["FIRST_TERM_ONLY", "SIGN_PRODUCT_ERROR"]],
  ["AE_COEFF_SQUARE", "Squaring a term with a coefficient", 3, ["AE_MONO_MONO"], ["COEFFICIENT_NOT_SQUARED"]],
  ["AE_BINOMIAL_BINOMIAL", "Multiplying two binomials", 3, ["AE_MONO_POLY"], ["FIRST_LAST_ONLY", "COMBINED_UNLIKE_TERMS"]],
  ["AE_BINOMIAL_TRINOMIAL", "Multiplying a binomial by a trinomial", 4, ["AE_BINOMIAL_BINOMIAL"], ["MISSED_A_PRODUCT"]],
  ["AE_IDENTITY_SQ_PLUS", "(a + b)² = a² + 2ab + b²", 4, ["AE_BINOMIAL_BINOMIAL"], ["SQUARE_DISTRIBUTES", "MIDDLE_NOT_DOUBLED"]],
  ["AE_IDENTITY_SQ_MINUS", "(a − b)² = a² − 2ab + b²", 4, ["AE_IDENTITY_SQ_PLUS"], ["WRONG_LAST_SIGN", "SQUARE_DISTRIBUTES"]],
  ["AE_IDENTITY_DIFF", "(a + b)(a − b) = a² − b²", 4, ["AE_BINOMIAL_BINOMIAL"], ["KEPT_MIDDLE_TERM", "WRONG_LAST_SIGN"]],
  ["AE_IDENTITY_XAB", "(x + a)(x + b) = x² + (a + b)x + ab", 4, ["AE_BINOMIAL_BINOMIAL"], ["SWAPPED_PRODUCT_SUM"]],
  ["AE_IDENTITY_NUMBERS", "Using identities for mental arithmetic", 5, ["AE_IDENTITY_SQ_PLUS", "AE_IDENTITY_DIFF"], ["IDENTITY_NOT_SEEN"]],
  ["AE_IDENTITY_CHOOSE", "Choosing the identity", 5, ["AE_IDENTITY_SQ_MINUS", "AE_IDENTITY_DIFF", "AE_IDENTITY_XAB"], ["SHAPE_MISREAD"]],
], {
  COEFFICIENT_SIGN_DROPPED: "Gives a coefficient without its sign.",
  UNLIKE_AS_LIKE: "Treats terms with different letters or powers as like terms.",
  SIGN_LOST_ON_SUBSTITUTION: "Drops the minus sign when putting a negative value in.",
  POWER_OF_NEGATIVE: "Works out (−2)² as −4.",
  COMBINED_UNLIKE_TERMS: "Adds unlike terms together.",
  SUBTRACTED_FIRST_TERM_ONLY: "Subtracts only the first term of the bracket.",
  ADDED_COEFFICIENTS: "Adds coefficients when multiplying.",
  MULTIPLIED_EXPONENTS: "Multiplies the powers instead of adding them.",
  FIRST_TERM_ONLY: "Multiplies only the first term inside the bracket.",
  SIGN_PRODUCT_ERROR: "Gets the sign of a product wrong.",
  COEFFICIENT_NOT_SQUARED: "Squares the letter but not its coefficient: (3a)² = 3a².",
  FIRST_LAST_ONLY: "Multiplies only the first terms and the last terms.",
  MISSED_A_PRODUCT: "Leaves out one of the products.",
  SQUARE_DISTRIBUTES: "Writes (a + b)² = a² + b².",
  MIDDLE_NOT_DOUBLED: "Writes ab instead of 2ab for the middle term.",
  WRONG_LAST_SIGN: "Gets the sign of the last term wrong.",
  KEPT_MIDDLE_TERM: "Keeps a middle term in (a + b)(a − b).",
  SWAPPED_PRODUCT_SUM: "Uses the product of a and b for the x term and their sum for the number.",
  IDENTITY_NOT_SEEN: "Multiplies the long way without seeing the identity.",
  SHAPE_MISREAD: "Picks an identity that doesn't fit the expression.",
}, [
  ["AE_TERMS", "CHOICE", "easy", "EXPLORE", "What is the coefficient of x in 7 − 4xy − 5x?", ["−5", "5", "−4", "7"], [], ["COEFFICIENT_SIGN_DROPPED", "UNLIKE_AS_LIKE"]],
  ["AE_ADD_SUB", "EXPRESSION", "easy", "EXPLORE", "Add 3a − 2b + 5 and 4a + 6b − 8.", "7a + 4b - 3", [], ["COMBINED_UNLIKE_TERMS"], "3a - 2b + 5 + 4a + 6b - 8"],
  ["AE_ADD_SUB", "EXPRESSION", "medium", "EXPLORE", "Subtract 2x² − 3x + 1 from 5x² + x − 4.", "3x^2 + 4x - 5", [], ["SUBTRACTED_FIRST_TERM_ONLY"], "(5x^2 + x - 4) - (2x^2 - 3x + 1)"],
  ["AE_MONO_MONO", "EXPRESSION", "easy", "EXPLORE", "Multiply 4x²y by −3xy³.", "-12x^3y^4", [], ["ADDED_COEFFICIENTS", "MULTIPLIED_EXPONENTS"], "4x^2y * (-3xy^3)"],
  ["AE_MONO_POLY", "EXPRESSION", "easy", "EXPLORE", "Expand 3a(2a − 5b + 4).", "6a^2 - 15ab + 12a", [], ["FIRST_TERM_ONLY"], "3a(2a - 5b + 4)"],
  ["AE_MONO_POLY", "EXPRESSION", "medium", "EXPLORE", "Expand −2x(x² − 3x + 7).", "-2x^3 + 6x^2 - 14x", [], ["SIGN_PRODUCT_ERROR", "FIRST_TERM_ONLY"], "-2x(x^2 - 3x + 7)"],
  ["AE_BINOMIAL_BINOMIAL", "EXPRESSION", "easy", "EXPLORE", "Expand (x + 4)(x + 3).", "x^2 + 7x + 12", [], ["FIRST_LAST_ONLY"], "(x + 4)(x + 3)"],
  ["AE_BINOMIAL_BINOMIAL", "EXPRESSION", "medium", "EXPLORE", "Expand (2a − 3)(a + 5).", "2a^2 + 7a - 15", [], ["FIRST_LAST_ONLY", "COMBINED_UNLIKE_TERMS"], "(2a - 3)(a + 5)"],
  ["AE_IDENTITY_SQ_PLUS", "EXPRESSION", "easy", "EXPLORE", "Expand (x + 6)².", "x^2 + 12x + 36", [], ["SQUARE_DISTRIBUTES", "MIDDLE_NOT_DOUBLED"], "(x + 6)^2"],
  ["AE_IDENTITY_SQ_MINUS", "EXPRESSION", "easy", "EXPLORE", "Expand (y − 5)².", "y^2 - 10y + 25", [], ["WRONG_LAST_SIGN", "SQUARE_DISTRIBUTES"], "(y - 5)^2"],
  ["AE_IDENTITY_DIFF", "EXPRESSION", "easy", "EXPLORE", "Expand (m + 7)(m − 7).", "m^2 - 49", [], ["KEPT_MIDDLE_TERM", "WRONG_LAST_SIGN"], "(m + 7)(m - 7)"],
  ["AE_EVALUATE", "NUMBER", "medium", "EXPLORE", "Find the value of 2x² − 3x + 1 when x = −2.", "15", [], ["SIGN_LOST_ON_SUBSTITUTION", "POWER_OF_NEGATIVE"], "2(-2)^2 - 3(-2) + 1"],
  ["AE_IDENTITY_XAB", "EXPRESSION", "medium", "EXPLORE", "Expand (x − 2)(x + 9).", "x^2 + 7x - 18", [], ["SWAPPED_PRODUCT_SUM"], "(x - 2)(x + 9)"],

  ["AE_COEFF_SQUARE", "EXPRESSION", "medium", "DIAGNOSE", "Expand (3a + 2b)².", "9a^2 + 12ab + 4b^2", ["AE_IDENTITY_SQ_PLUS"], ["COEFFICIENT_NOT_SQUARED", "MIDDLE_NOT_DOUBLED"], "(3a + 2b)^2"],
  ["AE_IDENTITY_SQ_MINUS", "EXPRESSION", "hard", "DIAGNOSE", "Expand (4x − 3y)².", "16x^2 - 24xy + 9y^2", ["AE_COEFF_SQUARE"], ["COEFFICIENT_NOT_SQUARED", "WRONG_LAST_SIGN"], "(4x - 3y)^2"],
  ["AE_IDENTITY_DIFF", "EXPRESSION", "medium", "DIAGNOSE", "Expand (5p + 2q)(5p − 2q).", "25p^2 - 4q^2", ["AE_COEFF_SQUARE"], ["KEPT_MIDDLE_TERM", "COEFFICIENT_NOT_SQUARED"], "(5p + 2q)(5p - 2q)"],
  ["AE_BINOMIAL_TRINOMIAL", "EXPRESSION", "hard", "DIAGNOSE", "Expand (x + 2)(x² − 3x + 4).", "x^3 - x^2 - 2x + 8", [], ["MISSED_A_PRODUCT"], "(x + 2)(x^2 - 3x + 4)"],
  ["AE_IDENTITY_NUMBERS", "NUMBER", "medium", "DIAGNOSE", "Use an identity to work out 103 × 97.", "9991", [], ["IDENTITY_NOT_SEEN"], "103 * 97"],
  ["AE_IDENTITY_CHOOSE", "CHOICE", "medium", "DIAGNOSE", "Which identity is quickest for (2x − 7)(2x + 7)?", ["(a + b)(a − b) = a² − b²", "(a − b)² = a² − 2ab + b²", "(a + b)² = a² + 2ab + b²", "(x + a)(x + b) = x² + (a + b)x + ab"], [], ["SHAPE_MISREAD"]],

  ["AE_IDENTITY_NUMBERS", "NUMBER", "medium", "CONFIRM", "Use an identity to work out 99².", "9801", ["AE_IDENTITY_SQ_MINUS"], ["IDENTITY_NOT_SEEN", "WRONG_LAST_SIGN"], "99^2"],
  ["AE_ADD_SUB", "EXPRESSION", "hard", "CONFIRM", "Simplify (a + b)² − (a − b)².", "4ab", ["AE_IDENTITY_SQ_PLUS", "AE_IDENTITY_SQ_MINUS"], ["SUBTRACTED_FIRST_TERM_ONLY", "SQUARE_DISTRIBUTES"], "(a + b)^2 - (a - b)^2"],
  ["AE_IDENTITY_CHOOSE", "NUMBER", "hard", "CONFIRM", "a + b = 10 and ab = 21. Find a² + b².", "58", ["AE_IDENTITY_SQ_PLUS"], ["SHAPE_MISREAD", "MIDDLE_NOT_DOUBLED"], "10^2 - 2 * 21"],
  ["AE_IDENTITY_DIFF", "NUMBER", "medium", "CONFIRM", "Use an identity to work out 78² − 22².", "5600", ["AE_IDENTITY_NUMBERS"], ["KEPT_MIDDLE_TERM", "IDENTITY_NOT_SEEN"], "78^2 - 22^2"],
  ["AE_BINOMIAL_BINOMIAL", "CHOICE", "medium", "CONFIRM", "Rahul wrote (x + 3)(x + 5) = x² + 15. What did he miss?", ["The middle term 8x", "The x² term", "The number 15", "Nothing, it is right"], [], ["FIRST_LAST_ONLY"]],
  ["AE_IDENTITY_XAB", "EXPRESSION", "hard", "CONFIRM", "Expand (2y − 5)(2y − 1).", "4y^2 - 12y + 5", ["AE_COEFF_SQUARE"], ["SWAPPED_PRODUCT_SUM", "COEFFICIENT_NOT_SQUARED"], "(2y - 5)(2y - 1)"],
]);
