import { draftChapter } from "./draft";

/** The whole chapter. The BRACKETS diagnostic Cogna runs today covers only its signed-number and bracket skills. */
export const LINEAR_EQUATIONS = draftChapter("linear-equations", 2, [
  ["LE_SIGNED_ARITH", "Signed number arithmetic", 0, [], ["SIGN_SUM_ERROR", "SIGN_PRODUCT_ERROR"]],
  ["LE_EXPAND_BRACKET", "Expanding a bracket", 0, ["LE_SIGNED_ARITH"], ["FIRST_TERM_ONLY", "NEGATIVE_NOT_DISTRIBUTED"]],
  ["LE_COLLECT_LIKE", "Collecting like terms", 0, [], ["COMBINED_UNLIKE_TERMS"]],
  ["LE_WHAT_IS_SOLUTION", "What a solution is", 1, [], ["SUBSTITUTED_WRONGLY"]],
  ["LE_ONE_STEP", "One-step equations", 1, ["LE_SIGNED_ARITH"], ["INVERSE_OP_WRONG", "SIGN_KEPT_ON_TRANSPOSE"]],
  ["LE_FRACTIONAL_ANSWER", "Answers that are fractions or negative", 2, ["LE_ONE_STEP"], ["DIVIDED_WRONG_WAY"]],
  ["LE_CHECK", "Checking a solution by substituting", 2, ["LE_WHAT_IS_SOLUTION"], ["SUBSTITUTED_WRONGLY"]],
  ["LE_TWO_STEP", "Two-step equations", 2, ["LE_ONE_STEP"], ["UNDID_IN_WRONG_ORDER", "SIGN_KEPT_ON_TRANSPOSE"]],
  ["LE_TRANSPOSE", "Moving a term to the other side", 2, ["LE_ONE_STEP"], ["SIGN_KEPT_ON_TRANSPOSE", "MOVED_COEFFICIENT_AS_TERM"]],
  ["LE_VAR_BOTH_SIDES", "Letters on both sides", 3, ["LE_TRANSPOSE", "LE_COLLECT_LIKE"], ["SIGN_KEPT_ON_TRANSPOSE", "COMBINED_ACROSS_EQUALS"]],
  ["LE_BRACKETS", "Equations with brackets", 3, ["LE_EXPAND_BRACKET", "LE_VAR_BOTH_SIDES"], ["FIRST_TERM_ONLY", "NEGATIVE_NOT_DISTRIBUTED"]],
  ["LE_FRACTIONS", "Equations with fractions", 3, ["LE_TWO_STEP"], ["LCM_NOT_ALL_TERMS", "NUMERATOR_NOT_BRACKETED"]],
  ["LE_REDUCIBLE", "Equations with the letter in a denominator", 4, ["LE_FRACTIONS", "LE_BRACKETS"], ["CROSS_MULTIPLIED_WRONG", "NUMERATOR_NOT_BRACKETED"]],
  ["LE_FORM_EQUATION", "Writing an equation from words", 4, ["LE_WHAT_IS_SOLUTION"], ["WRONG_RELATIONSHIP", "ANSWERED_WRONG_QUANTITY"]],
  ["LE_WORD_NUMBERS", "Number, age and digit problems", 5, ["LE_FORM_EQUATION", "LE_VAR_BOTH_SIDES"], ["WRONG_RELATIONSHIP", "ANSWERED_WRONG_QUANTITY"]],
  ["LE_WORD_CONSECUTIVE", "Consecutive number problems", 5, ["LE_FORM_EQUATION", "LE_COLLECT_LIKE"], ["CONSECUTIVE_ODD_AS_PLUS_ONE", "ANSWERED_WRONG_QUANTITY"]],
  ["LE_WORD_GEOMETRY", "Perimeter and angle problems", 5, ["LE_FORM_EQUATION"], ["WRONG_FORMULA", "ANSWERED_WRONG_QUANTITY"]],
], {
  SIGN_SUM_ERROR: "Gets the sign wrong when adding a positive and a negative.",
  SIGN_PRODUCT_ERROR: "Gets the sign of a product wrong.",
  FIRST_TERM_ONLY: "Multiplies only the first term inside the bracket.",
  NEGATIVE_NOT_DISTRIBUTED: "Multiplies by a negative outside the bracket but keeps the inside signs.",
  COMBINED_UNLIKE_TERMS: "Adds an x term and a number together.",
  SUBSTITUTED_WRONGLY: "Puts the value in for the letter but works the sides out wrongly.",
  INVERSE_OP_WRONG: "Undoes a step with the same operation instead of its inverse.",
  SIGN_KEPT_ON_TRANSPOSE: "Moves a term across the equals sign without changing its sign.",
  DIVIDED_WRONG_WAY: "Divides the coefficient by the number instead of the number by the coefficient.",
  UNDID_IN_WRONG_ORDER: "Divides before taking away the constant.",
  MOVED_COEFFICIENT_AS_TERM: "Moves a multiplier across as if it were added (2x = 15 → x = 15 − 2).",
  COMBINED_ACROSS_EQUALS: "Adds terms from opposite sides as if they were on one side.",
  LCM_NOT_ALL_TERMS: "Multiplies only the fractions by the LCM and not the whole numbers.",
  NUMERATOR_NOT_BRACKETED: "Loses the bracket around a numerator, so a minus in front hits only its first term.",
  CROSS_MULTIPLIED_WRONG: "Cross-multiplies but multiplies only one term of a bracket.",
  WRONG_RELATIONSHIP: "Writes the story as the wrong equation (for example, times instead of more than).",
  ANSWERED_WRONG_QUANTITY: "Solves for x but gives x when the question asked for something else.",
  CONSECUTIVE_ODD_AS_PLUS_ONE: "Writes consecutive odd numbers as x, x + 1, x + 2.",
  WRONG_FORMULA: "Uses the wrong perimeter or angle-sum fact.",
}, [
  ["LE_ONE_STEP", "NUMBER", "easy", "EXPLORE", "Solve x − 7 = −3.", "4", [], ["INVERSE_OP_WRONG", "SIGN_KEPT_ON_TRANSPOSE"], "x - 7 = -3"],
  ["LE_FRACTIONAL_ANSWER", "NUMBER", "easy", "EXPLORE", "Solve 6x = −9.", "-3/2", [], ["DIVIDED_WRONG_WAY"], "6x = -9"],
  ["LE_TWO_STEP", "NUMBER", "easy", "EXPLORE", "Solve 3x + 5 = 20.", "5", [], ["UNDID_IN_WRONG_ORDER", "SIGN_KEPT_ON_TRANSPOSE"], "3x + 5 = 20"],
  ["LE_TWO_STEP", "NUMBER", "medium", "EXPLORE", "Solve x/4 − 3 = 2.", "20", [], ["UNDID_IN_WRONG_ORDER"], "x/4 - 3 = 2"],
  ["LE_TRANSPOSE", "CHOICE", "easy", "EXPLORE", "In 2x + 9 = 15, what happens to the +9 when it moves to the other side?", ["It becomes −9: 2x = 15 − 9", "It stays +9: 2x = 15 + 9", "It divides: 2x = 15 ÷ 9", "It multiplies: 2x = 15 × 9"], [], ["SIGN_KEPT_ON_TRANSPOSE", "MOVED_COEFFICIENT_AS_TERM"]],
  ["LE_CHECK", "CHOICE", "easy", "EXPLORE", "Is x = 3 a solution of 4x − 5 = 2x + 1?", ["Yes, both sides equal 7", "No, the sides are 7 and 6", "No, x must be 4", "Only if x is negative"], [], ["SUBSTITUTED_WRONGLY"]],
  ["LE_COLLECT_LIKE", "EXPRESSION", "easy", "EXPLORE", "Simplify 5x + 3 − 2x + 4.", "3x + 7", [], ["COMBINED_UNLIKE_TERMS"], "5x + 3 - 2x + 4"],
  ["LE_VAR_BOTH_SIDES", "NUMBER", "medium", "EXPLORE", "Solve 5x − 4 = 2x + 11.", "5", ["LE_COLLECT_LIKE"], ["SIGN_KEPT_ON_TRANSPOSE", "COMBINED_ACROSS_EQUALS"], "5x - 4 = 2x + 11"],
  ["LE_VAR_BOTH_SIDES", "NUMBER", "medium", "EXPLORE", "Solve 7 − 3x = x − 9.", "4", [], ["SIGN_KEPT_ON_TRANSPOSE"], "7 - 3x = x - 9"],
  ["LE_EXPAND_BRACKET", "EXPRESSION", "easy", "EXPLORE", "Expand −3(2x − 5).", "-6x + 15", [], ["FIRST_TERM_ONLY", "NEGATIVE_NOT_DISTRIBUTED"], "-3(2x - 5)"],
  ["LE_BRACKETS", "NUMBER", "medium", "EXPLORE", "Solve 4(x − 2) = 2(x + 3).", "7", ["LE_VAR_BOTH_SIDES"], ["FIRST_TERM_ONLY", "SIGN_KEPT_ON_TRANSPOSE"], "4(x - 2) = 2(x + 3)"],
  ["LE_BRACKETS", "NUMBER", "hard", "EXPLORE", "Solve 5 − 2(x − 3) = 3x − 4.", "3", [], ["NEGATIVE_NOT_DISTRIBUTED"], "5 - 2(x - 3) = 3x - 4"],
  ["LE_FORM_EQUATION", "CHOICE", "easy", "EXPLORE", "A number is doubled and then increased by 7 to give 31. Which equation fits?", ["2x + 7 = 31", "2(x + 7) = 31", "x + 7 × 2 = 31", "2x = 31 + 7"], [], ["WRONG_RELATIONSHIP"]],

  ["LE_FRACTIONS", "NUMBER", "medium", "DIAGNOSE", "Solve x/2 + x/3 = 10.", "12", [], ["LCM_NOT_ALL_TERMS"], "x/2 + x/3 = 10"],
  ["LE_FRACTIONS", "NUMBER", "hard", "DIAGNOSE", "Solve (x − 1)/3 − (x + 2)/4 = 1.", "22", ["LE_BRACKETS"], ["NUMERATOR_NOT_BRACKETED", "LCM_NOT_ALL_TERMS"], "(x - 1)/3 - (x + 2)/4 = 1"],
  ["LE_REDUCIBLE", "NUMBER", "hard", "DIAGNOSE", "Solve (2x + 3)/(x − 1) = 3.", "6", [], ["CROSS_MULTIPLIED_WRONG", "NUMERATOR_NOT_BRACKETED"], "2x + 3 = 3(x - 1)"],
  ["LE_WORD_NUMBERS", "NUMBER", "medium", "DIAGNOSE", "Meena's mother is 4 times as old as Meena. In 5 years she will be 3 times as old as Meena. How old is Meena now?", "10", ["LE_BRACKETS"], ["WRONG_RELATIONSHIP", "ANSWERED_WRONG_QUANTITY"], "4x + 5 = 3(x + 5)"],
  ["LE_WORD_CONSECUTIVE", "NUMBER", "medium", "DIAGNOSE", "Three consecutive odd numbers add up to 57. What is the smallest?", "17", [], ["CONSECUTIVE_ODD_AS_PLUS_ONE", "ANSWERED_WRONG_QUANTITY"], "x + (x + 2) + (x + 4) = 57"],
  ["LE_WORD_GEOMETRY", "NUMBER", "medium", "DIAGNOSE", "A rectangle is 4 cm longer than it is wide. Its perimeter is 40 cm. How wide is it, in cm?", "8", [], ["WRONG_FORMULA", "ANSWERED_WRONG_QUANTITY"], "2(x + 4 + x) = 40"],

  ["LE_VAR_BOTH_SIDES", "NUMBER", "hard", "CONFIRM", "Solve 3(2x − 1) − 2(x − 4) = 5 − x.", "0", ["LE_BRACKETS"], ["NEGATIVE_NOT_DISTRIBUTED", "SIGN_KEPT_ON_TRANSPOSE"], "3(2x - 1) - 2(x - 4) = 5 - x"],
  ["LE_FRACTIONS", "NUMBER", "hard", "CONFIRM", "Solve 3x/4 − 2 = x/6 + 5.", "12", ["LE_VAR_BOTH_SIDES"], ["LCM_NOT_ALL_TERMS", "SIGN_KEPT_ON_TRANSPOSE"], "3x/4 - 2 = x/6 + 5"],
  ["LE_REDUCIBLE", "NUMBER", "hard", "CONFIRM", "Solve (x + 5)/(x − 3) = 3/2.", "19", [], ["CROSS_MULTIPLIED_WRONG"], "2(x + 5) = 3(x - 3)"],
  ["LE_WORD_NUMBERS", "NUMBER", "hard", "CONFIRM", "The digits of a two-digit number add up to 9. Swapping the digits gives a number 27 more than the original. What is the original number?", "36", ["LE_FORM_EQUATION"], ["ANSWERED_WRONG_QUANTITY", "WRONG_RELATIONSHIP"]],
  ["LE_WORD_GEOMETRY", "NUMBER", "medium", "CONFIRM", "The angles of a triangle are x°, 2x° and 3x°. What is the largest angle, in degrees?", "90", [], ["ANSWERED_WRONG_QUANTITY", "WRONG_FORMULA"]],
  ["LE_CHECK", "CHOICE", "medium", "CONFIRM", "Asha solved 2(x + 3) = 14 and got x = 5.5. What went wrong?", ["She multiplied only the x by 2, not the 3", "Nothing, x = 5.5 is right", "She should have added 3", "She divided 14 by 3"], ["LE_EXPAND_BRACKET"], ["FIRST_TERM_ONLY", "SUBSTITUTED_WRONGLY"]],
]);
