import { draftChapter } from "./draft";

export const SQUARES_ROOTS = draftChapter("squares-roots", 5, [
  ["SQ_SQUARE", "Squaring a number", 0, [], ["DOUBLED_NOT_SQUARED"]],
  ["SQ_PRIME_FACTOR", "Prime factorisation", 0, [], ["NOT_PRIME_FACTORS"]],
  ["SQ_PERFECT", "Perfect squares and their last digits", 1, ["SQ_SQUARE"], ["LAST_DIGIT_RULE_REVERSED"]],
  ["SQ_UNITS_DIGIT", "Units digit of a square", 1, ["SQ_SQUARE"], ["UNITS_DIGIT_NOT_SQUARED"]],
  ["SQ_ROOT_MEANING", "What a square root is", 1, ["SQ_SQUARE"], ["HALVED_NOT_ROOTED"]],
  ["SQ_PATTERNS", "Square patterns", 2, ["SQ_SQUARE"], ["BETWEEN_COUNT_OFF_BY_ONE", "ODD_SUM_MISCOUNTED"]],
  ["SQ_TRIPLETS", "Pythagorean triplets", 2, ["SQ_SQUARE"], ["ADDED_NOT_SQUARED", "WRONG_FORMULA_TRIPLET"]],
  ["SQ_ROOT_FACTOR", "Square root by prime factorisation", 2, ["SQ_PRIME_FACTOR", "SQ_ROOT_MEANING"], ["TOOK_EVERY_FACTOR", "UNPAIRED_FACTOR_KEPT"]],
  ["SQ_MAKE_PERFECT", "Smallest multiplier or divisor for a perfect square", 3, ["SQ_ROOT_FACTOR"], ["MULTIPLIED_BY_PAIRED_FACTOR"]],
  ["SQ_DIVISION_METHOD", "Square root by long division", 3, ["SQ_ROOT_MEANING"], ["WRONG_PAIRING", "DIGIT_NOT_DOUBLED"]],
  ["SQ_FRACTION_ROOT", "Square roots of fractions", 3, ["SQ_ROOT_MEANING"], ["ROOTED_ONE_PART", "MIXED_NUMBER_ROOTED_IN_PARTS"]],
  ["SQ_ESTIMATE", "Estimating a square root", 3, ["SQ_PERFECT"], ["ROOT_NOT_BETWEEN_SQUARES", "WENT_TO_SMALLER_SQUARE"]],
  ["SQ_DECIMAL_ROOT", "Square roots of decimals", 4, ["SQ_DIVISION_METHOD"], ["DECIMAL_PLACES_WRONG"]],
  ["SQ_DIGITS", "Number of digits in a square root", 4, ["SQ_DIVISION_METHOD"], ["DIGITS_COUNTED_WRONG"]],
  ["SQ_WORD", "Area and arrangement problems", 4, ["SQ_ROOT_FACTOR"], ["WRONG_OPERATION"]],
], {
  DOUBLED_NOT_SQUARED: "Multiplies by 2 instead of by itself.",
  NOT_PRIME_FACTORS: "Leaves a factor that isn't prime.",
  LAST_DIGIT_RULE_REVERSED: "Thinks a number ending in 2, 3, 7 or 8 can be a perfect square.",
  UNITS_DIGIT_NOT_SQUARED: "Gives the units digit of the number, not of its square.",
  HALVED_NOT_ROOTED: "Halves the number instead of taking the square root.",
  BETWEEN_COUNT_OFF_BY_ONE: "Gets the count of numbers between two squares off by one.",
  ODD_SUM_MISCOUNTED: "Doesn't see that the first n odd numbers add up to n².",
  ADDED_NOT_SQUARED: "Adds the sides instead of their squares.",
  WRONG_FORMULA_TRIPLET: "Uses the triplet 2m, m² − 1, m² + 1 with the wrong m.",
  TOOK_EVERY_FACTOR: "Multiplies every prime factor instead of one from each pair.",
  UNPAIRED_FACTOR_KEPT: "Keeps a factor that has no partner.",
  MULTIPLIED_BY_PAIRED_FACTOR: "Multiplies or divides by a factor that already has a partner.",
  WRONG_PAIRING: "Pairs the digits from the left instead of from the units place.",
  DIGIT_NOT_DOUBLED: "Forgets to double the quotient so far for the next divisor.",
  ROOTED_ONE_PART: "Takes the root of only the top or only the bottom.",
  MIXED_NUMBER_ROOTED_IN_PARTS: "Takes the root of the whole number and the fraction separately.",
  ROOT_NOT_BETWEEN_SQUARES: "Doesn't place the root between the roots of the nearest squares.",
  WENT_TO_SMALLER_SQUARE: "Goes down to the square below when the question asks what to add.",
  DECIMAL_PLACES_WRONG: "Puts the decimal point in the wrong place.",
  DIGITS_COUNTED_WRONG: "Counts the root's digits as the number's digits.",
  WRONG_OPERATION: "Divides or halves when the story needs a square root.",
}, [
  ["SQ_SQUARE", "NUMBER", "easy", "EXPLORE", "What is 13²?", "169", [], ["DOUBLED_NOT_SQUARED"], "13^2"],
  ["SQ_UNITS_DIGIT", "NUMBER", "easy", "EXPLORE", "What is the units digit of 257²?", "9", [], ["UNITS_DIGIT_NOT_SQUARED"]],
  ["SQ_PERFECT", "CHOICE", "easy", "EXPLORE", "Which of these cannot be a perfect square?", ["1057", "1024", "1369", "2401"], [], ["LAST_DIGIT_RULE_REVERSED"]],
  ["SQ_PATTERNS", "NUMBER", "medium", "EXPLORE", "How many whole numbers lie between 12² and 13²?", "24", [], ["BETWEEN_COUNT_OFF_BY_ONE"], "13^2 - 12^2 - 1"],
  ["SQ_PATTERNS", "NUMBER", "easy", "EXPLORE", "What is 1 + 3 + 5 + 7 + 9 + 11 + 13?", "49", [], ["ODD_SUM_MISCOUNTED"], "1 + 3 + 5 + 7 + 9 + 11 + 13"],
  ["SQ_ROOT_MEANING", "NUMBER", "easy", "EXPLORE", "What is the square root of 81?", "9", [], ["HALVED_NOT_ROOTED"], "x^2 = 81"],
  ["SQ_PRIME_FACTOR", "CHOICE", "easy", "EXPLORE", "Which is 144 written as a product of primes?", ["2⁴ × 3²", "12 × 12", "2³ × 18", "2⁴ × 9"], [], ["NOT_PRIME_FACTORS"]],
  ["SQ_ROOT_FACTOR", "NUMBER", "medium", "EXPLORE", "Find the square root of 1764 by prime factorisation.", "42", [], ["TOOK_EVERY_FACTOR", "UNPAIRED_FACTOR_KEPT"], "x^2 = 1764"],
  ["SQ_TRIPLETS", "NUMBER", "medium", "EXPLORE", "A Pythagorean triplet has 8 as its smallest member. What is its largest member?", "17", [], ["WRONG_FORMULA_TRIPLET"], "4^2 + 1"],
  ["SQ_TRIPLETS", "CHOICE", "easy", "EXPLORE", "Is 6, 8, 10 a Pythagorean triplet?", ["Yes, 36 + 64 = 100", "No, 6 + 8 is not 10", "No, 10 is not a square", "Only if the numbers are prime"], [], ["ADDED_NOT_SQUARED"]],
  ["SQ_FRACTION_ROOT", "NUMBER", "easy", "EXPLORE", "What is the square root of 49/64?", "7/8", [], ["ROOTED_ONE_PART"], "x^2 = 49/64"],
  ["SQ_ESTIMATE", "CHOICE", "medium", "EXPLORE", "Between which two whole numbers does the square root of 250 lie?", ["15 and 16", "12 and 13", "25 and 26", "125 and 126"], [], ["ROOT_NOT_BETWEEN_SQUARES"]],
  ["SQ_ROOT_MEANING", "CHOICE", "easy", "EXPLORE", "A square has an area of 64 cm². How long is each side?", ["8 cm", "16 cm", "32 cm", "4096 cm"], [], ["HALVED_NOT_ROOTED"]],

  ["SQ_MAKE_PERFECT", "NUMBER", "medium", "DIAGNOSE", "What is the smallest number you must multiply 180 by to get a perfect square?", "5", ["SQ_PRIME_FACTOR"], ["MULTIPLIED_BY_PAIRED_FACTOR"]],
  ["SQ_MAKE_PERFECT", "NUMBER", "hard", "DIAGNOSE", "What is the smallest number you must divide 2028 by to get a perfect square?", "3", ["SQ_ROOT_FACTOR"], ["MULTIPLIED_BY_PAIRED_FACTOR", "UNPAIRED_FACTOR_KEPT"]],
  ["SQ_DIVISION_METHOD", "NUMBER", "medium", "DIAGNOSE", "Find the square root of 5329 by long division.", "73", [], ["WRONG_PAIRING", "DIGIT_NOT_DOUBLED"], "x^2 = 5329"],
  ["SQ_DECIMAL_ROOT", "NUMBER", "hard", "DIAGNOSE", "Find the square root of 17.64.", "4.2", [], ["DECIMAL_PLACES_WRONG"], "x^2 = 1764/100"],
  ["SQ_DIGITS", "NUMBER", "medium", "DIAGNOSE", "Without working it out, how many digits does the square root of 390625 have?", "3", [], ["DIGITS_COUNTED_WRONG"]],
  ["SQ_WORD", "NUMBER", "medium", "DIAGNOSE", "2025 plants are planted in rows, with as many plants in each row as there are rows. How many rows are there?", "45", [], ["WRONG_OPERATION"], "x^2 = 2025"],

  ["SQ_ROOT_FACTOR", "NUMBER", "hard", "CONFIRM", "Find the square root of 7056.", "84", ["SQ_PRIME_FACTOR"], ["UNPAIRED_FACTOR_KEPT", "TOOK_EVERY_FACTOR"], "x^2 = 7056"],
  ["SQ_ESTIMATE", "NUMBER", "hard", "CONFIRM", "What is the smallest number you must add to 1300 to make a perfect square?", "69", ["SQ_DIVISION_METHOD"], ["WENT_TO_SMALLER_SQUARE", "ROOT_NOT_BETWEEN_SQUARES"], "37^2 - 1300"],
  ["SQ_FRACTION_ROOT", "NUMBER", "hard", "CONFIRM", "Find the square root of the mixed number 3 1/16.", "7/4", ["SQ_ROOT_MEANING"], ["MIXED_NUMBER_ROOTED_IN_PARTS", "ROOTED_ONE_PART"], "x^2 = 49/16"],
  ["SQ_TRIPLETS", "NUMBER", "hard", "CONFIRM", "A 13 m ladder leans against a wall and reaches a window 12 m up. How far is the foot of the ladder from the wall, in m?", "5", ["SQ_ROOT_MEANING"], ["ADDED_NOT_SQUARED"], "x^2 + 12^2 = 13^2"],
  ["SQ_UNITS_DIGIT", "CHOICE", "medium", "CONFIRM", "Whose square ends in 6?", ["24", "23", "25", "22"], [], ["UNITS_DIGIT_NOT_SQUARED"]],
  ["SQ_DIVISION_METHOD", "NUMBER", "hard", "CONFIRM", "Find the square root of 998001.", "999", [], ["WRONG_PAIRING", "DIGIT_NOT_DOUBLED"], "x^2 = 998001"],
]);
