import { draftChapter } from "./draft";

/** Tables, histograms and pie charts are given as numbers in the question, so nothing needs a picture. */
export const DATA_HANDLING = draftChapter("data-handling", 4, [
  ["DH_MEAN", "Mean of data", 0, [], ["DIVIDED_BY_WRONG_COUNT", "ADDED_WRONG"]],
  ["DH_MODE_MEDIAN", "Mode and median", 0, [], ["MEDIAN_NOT_SORTED", "MODE_AS_LARGEST"]],
  ["DH_TALLY", "Counting with a frequency table", 0, [], ["MISCOUNTED_TALLY"]],
  ["DH_PERCENT_OF_TOTAL", "Part of a whole as a fraction", 0, [], ["DIVIDED_BY_PART"]],
  ["DH_OUTCOMES", "Listing the outcomes of an experiment", 0, [], ["MISSED_OUTCOMES", "ORDER_IGNORED"]],
  ["DH_CLASS_INTERVAL", "Class intervals and their limits", 1, ["DH_TALLY"], ["UPPER_LIMIT_INCLUDED", "WIDTH_AS_COUNT"]],
  ["DH_PIE_ANGLE", "Central angle in a pie chart", 1, ["DH_PERCENT_OF_TOTAL"], ["USED_100_NOT_360", "DIVIDED_BY_PART"]],
  ["DH_EQUALLY_LIKELY", "Equally likely outcomes", 1, ["DH_OUTCOMES"], ["ALL_EVENTS_EQUALLY_LIKELY"]],
  ["DH_GROUP_DATA", "Putting data into groups", 2, ["DH_CLASS_INTERVAL"], ["UPPER_LIMIT_INCLUDED"]],
  ["DH_HISTOGRAM_READ", "Reading a histogram", 2, ["DH_CLASS_INTERVAL"], ["READ_WRONG_BAR", "ADDED_LIMITS"]],
  ["DH_PIE_READ", "Reading a pie chart", 2, ["DH_PIE_ANGLE"], ["USED_100_NOT_360"]],
  ["DH_PROBABILITY", "Probability of an event", 2, ["DH_EQUALLY_LIKELY"], ["FAVOURABLE_OVER_UNFAVOURABLE", "COUNTED_OUTCOMES_WRONG"]],
  ["DH_PROB_COMPLEMENT", "Probability that an event doesn't happen", 3, ["DH_PROBABILITY"], ["COMPLEMENT_NOT_FROM_ONE"]],
  ["DH_PROB_RANGE", "Probability lies between 0 and 1", 3, ["DH_PROBABILITY"], ["PROBABILITY_ABOVE_ONE"]],
  ["DH_CHOOSE_GRAPH", "Choosing the right graph", 3, ["DH_HISTOGRAM_READ", "DH_PIE_READ"], ["WRONG_GRAPH_FOR_DATA"]],
], {
  DIVIDED_BY_WRONG_COUNT: "Divides the total by the wrong number of values.",
  ADDED_WRONG: "Makes an addition slip in the total.",
  MEDIAN_NOT_SORTED: "Takes the middle value without putting the data in order.",
  MODE_AS_LARGEST: "Gives the largest value instead of the most frequent.",
  MISCOUNTED_TALLY: "Miscounts how many times a value appears.",
  DIVIDED_BY_PART: "Divides the total by the part instead of the part by the total.",
  MISSED_OUTCOMES: "Leaves out some possible outcomes.",
  ORDER_IGNORED: "Counts HT and TH as one outcome.",
  UPPER_LIMIT_INCLUDED: "Puts a value equal to the upper limit in the lower group.",
  WIDTH_AS_COUNT: "Gives the number of values instead of the interval width.",
  USED_100_NOT_360: "Uses 100 instead of 360° for a pie chart.",
  ALL_EVENTS_EQUALLY_LIKELY: "Thinks every named outcome is equally likely, however many ways it can happen.",
  READ_WRONG_BAR: "Reads the wrong bar or adds the wrong bars.",
  ADDED_LIMITS: "Adds the class limits instead of the frequencies.",
  FAVOURABLE_OVER_UNFAVOURABLE: "Divides favourable outcomes by unfavourable ones, not by all outcomes.",
  COUNTED_OUTCOMES_WRONG: "Counts the outcomes that fit the event wrongly (for example, includes the boundary).",
  COMPLEMENT_NOT_FROM_ONE: "Doesn't take the probability away from 1.",
  PROBABILITY_ABOVE_ONE: "Accepts a probability greater than 1.",
  WRONG_GRAPH_FOR_DATA: "Chooses a graph that doesn't suit the data.",
}, [
  ["DH_MEAN", "NUMBER", "easy", "EXPLORE", "Find the mean of 12, 15, 9, 20 and 14.", "14", [], ["DIVIDED_BY_WRONG_COUNT", "ADDED_WRONG"], "(12 + 15 + 9 + 20 + 14) / 5"],
  ["DH_MODE_MEDIAN", "NUMBER", "easy", "EXPLORE", "Find the median of 7, 3, 9, 5, 4.", "5", [], ["MEDIAN_NOT_SORTED"]],
  ["DH_TALLY", "NUMBER", "easy", "EXPLORE", "Ten students' scores: 3, 5, 3, 2, 5, 5, 4, 3, 5, 1. How many scored 5?", "4", [], ["MISCOUNTED_TALLY"]],
  ["DH_CLASS_INTERVAL", "NUMBER", "easy", "EXPLORE", "What is the width of the class interval 20–30?", "10", [], ["WIDTH_AS_COUNT"], "30 - 20"],
  ["DH_CLASS_INTERVAL", "CHOICE", "medium", "EXPLORE", "Data is grouped as 10–20, 20–30 and 30–40. Which group does a score of 20 go in?", ["20–30", "10–20", "Both groups", "Neither group"], [], ["UPPER_LIMIT_INCLUDED"]],
  ["DH_GROUP_DATA", "NUMBER", "medium", "EXPLORE", "Marks: 12, 25, 18, 30, 22, 19, 29, 20. How many are in the group 20–30 (20 included, 30 not)?", "4", [], ["UPPER_LIMIT_INCLUDED"]],
  ["DH_HISTOGRAM_READ", "NUMBER", "medium", "EXPLORE", "A histogram of heights shows 140–145 cm: 4 students, 145–150 cm: 9, 150–155 cm: 6, 155–160 cm: 3. How many students are 150 cm or taller?", "9", [], ["READ_WRONG_BAR", "ADDED_LIMITS"], "6 + 3"],
  ["DH_PERCENT_OF_TOTAL", "NUMBER", "easy", "EXPLORE", "Of 40 students, 10 walk to school. What fraction of the class walks?", "1/4", [], ["DIVIDED_BY_PART"], "10 / 40"],
  ["DH_PIE_ANGLE", "NUMBER", "medium", "EXPLORE", "In a class of 36, 9 like cricket best. What angle shows cricket in a pie chart, in degrees?", "90", [], ["USED_100_NOT_360", "DIVIDED_BY_PART"], "9 / 36 * 360"],
  ["DH_PIE_READ", "NUMBER", "medium", "EXPLORE", "A pie chart shows 600 people's favourite drinks. Tea has an angle of 120°. How many people chose tea?", "200", [], ["USED_100_NOT_360"], "120 / 360 * 600"],
  ["DH_OUTCOMES", "NUMBER", "easy", "EXPLORE", "How many different outcomes are there when you roll one die?", "6", [], ["MISSED_OUTCOMES"]],
  ["DH_PROBABILITY", "NUMBER", "easy", "EXPLORE", "A bag has 3 red and 5 blue balls. One is picked without looking. What is the probability that it is red?", "3/8", [], ["FAVOURABLE_OVER_UNFAVOURABLE"], "3 / (3 + 5)"],
  ["DH_EQUALLY_LIKELY", "CHOICE", "medium", "EXPLORE", "A spinner has 4 equal parts coloured red, red, blue and green. Are red, blue and green equally likely?", ["No, red is twice as likely as each other colour", "Yes, there are three colours", "Yes, every spin is random", "No, green is the most likely"], [], ["ALL_EVENTS_EQUALLY_LIKELY"]],

  ["DH_PROBABILITY", "NUMBER", "medium", "DIAGNOSE", "A die is rolled. What is the probability of getting a number greater than 4?", "1/3", ["DH_OUTCOMES"], ["COUNTED_OUTCOMES_WRONG", "MISSED_OUTCOMES"], "2 / 6"],
  ["DH_PROB_COMPLEMENT", "NUMBER", "medium", "DIAGNOSE", "The probability that it rains tomorrow is 3/10. What is the probability that it doesn't rain?", "7/10", [], ["COMPLEMENT_NOT_FROM_ONE"], "1 - 3/10"],
  ["DH_PROB_RANGE", "CHOICE", "medium", "DIAGNOSE", "Which of these cannot be a probability?", ["5/4", "0", "1", "3/7"], [], ["PROBABILITY_ABOVE_ONE"]],
  ["DH_PIE_ANGLE", "NUMBER", "hard", "DIAGNOSE", "A family spends ₹20000 a month, ₹5000 of it on food. What angle shows food in a pie chart, in degrees?", "90", [], ["DIVIDED_BY_PART", "USED_100_NOT_360"], "5000 / 20000 * 360"],
  ["DH_HISTOGRAM_READ", "CHOICE", "medium", "DIAGNOSE", "A histogram of ages shows 10–20: 5 people, 20–30: 12, 30–40: 8. Which group has the most people?", ["20–30", "30–40", "10–20", "They are all the same"], [], ["READ_WRONG_BAR"]],
  ["DH_MEAN", "NUMBER", "medium", "DIAGNOSE", "The mean of 5 numbers is 18. Four of them are 15, 20, 12 and 25. What is the fifth?", "18", [], ["DIVIDED_BY_WRONG_COUNT"], "5 * 18 - 15 - 20 - 12 - 25"],

  ["DH_PROBABILITY", "NUMBER", "hard", "CONFIRM", "Two coins are tossed together. What is the probability of getting exactly one head?", "1/2", ["DH_OUTCOMES"], ["MISSED_OUTCOMES", "ORDER_IGNORED"], "2 / 4"],
  ["DH_GROUP_DATA", "NUMBER", "hard", "CONFIRM", "Ages: 11, 14, 15, 12, 16, 15, 13, 14, 15, 10. With groups 10–12, 12–14, 14–16, 16–18 (lower limit included), how many are in 14–16?", "5", [], ["UPPER_LIMIT_INCLUDED"]],
  ["DH_PIE_READ", "NUMBER", "hard", "CONFIRM", "A pie chart shows 720 students' favourite sports. Football has 150° and hockey has 60°. How many more students chose football than hockey?", "180", [], ["USED_100_NOT_360"], "(150 - 60) / 360 * 720"],
  ["DH_PROB_COMPLEMENT", "NUMBER", "hard", "CONFIRM", "A box has 12 bulbs and 3 of them are broken. One is picked at random. What is the probability that it works?", "3/4", ["DH_PROBABILITY"], ["COMPLEMENT_NOT_FROM_ONE", "FAVOURABLE_OVER_UNFAVOURABLE"], "1 - 3/12"],
  ["DH_CHOOSE_GRAPH", "CHOICE", "medium", "CONFIRM", "Which graph best shows how a family's money is split between food, rent, travel and savings?", ["A pie chart", "A histogram", "A line graph", "A double bar graph of years"], [], ["WRONG_GRAPH_FOR_DATA"]],
  ["DH_MODE_MEDIAN", "NUMBER", "medium", "CONFIRM", "Find the mode of 4, 7, 2, 7, 9, 4, 7, 1.", "7", [], ["MODE_AS_LARGEST"]],
]);
