import { draftChapter } from "./draft";

/** No diagrams: every figure is described in words, so answers are numbers or choices. */
export const QUADRILATERALS = draftChapter("quadrilaterals", 3, [
  ["QD_POLYGON_TYPES", "Polygons, convex and concave", 0, [], ["CONCAVE_CONVEX_SWAPPED"]],
  ["QD_DIAGONALS", "Diagonals of a polygon", 0, ["QD_POLYGON_TYPES"], ["COUNTED_SIDES_AS_DIAGONALS", "DOUBLE_COUNTED"]],
  ["QD_ANGLE_SUM_TRIANGLE", "Angles of a triangle add to 180°", 0, [], ["USED_360"]],
  ["QD_ANGLE_SUM_POLYGON", "Interior angle sum (n − 2) × 180°", 1, ["QD_ANGLE_SUM_TRIANGLE"], ["USED_N_TIMES_180", "USED_360"]],
  ["QD_EXTERIOR_SUM", "Exterior angles add to 360°", 1, [], ["EXTERIOR_SUM_DEPENDS_ON_N"]],
  ["QD_INT_EXT_PAIR", "An interior and its exterior angle add to 180°", 1, [], ["USED_360"]],
  ["QD_REGULAR_INTERIOR", "Each angle of a regular polygon", 2, ["QD_ANGLE_SUM_POLYGON"], ["FORGOT_TO_DIVIDE", "USED_N_TIMES_180"]],
  ["QD_EXTERIOR_REGULAR", "Exterior angle and sides of a regular polygon", 2, ["QD_EXTERIOR_SUM"], ["USED_INTERIOR_AS_EXTERIOR", "DIVIDED_WRONG_WAY"]],
  ["QD_QUAD_ANGLES", "Angles of a quadrilateral add to 360°", 2, ["QD_ANGLE_SUM_POLYGON"], ["USED_180"]],
  ["QD_PARALLELOGRAM_SIDES", "Parallelogram: opposite sides equal", 3, [], ["ADJACENT_SIDES_EQUAL"]],
  ["QD_PARALLELOGRAM_ANGLES", "Parallelogram: opposite angles equal, neighbours add to 180°", 3, ["QD_QUAD_ANGLES"], ["ADJACENT_ANGLES_EQUAL", "OPPOSITE_SUPPLEMENTARY"]],
  ["QD_PARALLELOGRAM_DIAGONALS", "Parallelogram: diagonals bisect each other", 3, ["QD_DIAGONALS"], ["DIAGONAL_HALF_MIXED_UP", "DIAGONALS_ASSUMED_EQUAL"]],
  ["QD_RHOMBUS", "Rhombus: diagonals are perpendicular bisectors", 4, ["QD_PARALLELOGRAM_DIAGONALS"], ["NOT_PERPENDICULAR", "DIAGONALS_ASSUMED_EQUAL"]],
  ["QD_RECTANGLE", "Rectangle: diagonals equal and bisect each other", 4, ["QD_PARALLELOGRAM_DIAGONALS"], ["DIAGONALS_PERPENDICULAR_ASSUMED"]],
  ["QD_SQUARE", "Square: every property at once", 4, ["QD_RHOMBUS", "QD_RECTANGLE"], ["SQUARE_NOT_RECTANGLE"]],
  ["QD_KITE", "Kite", 4, ["QD_DIAGONALS"], ["KITE_AS_PARALLELOGRAM"]],
  ["QD_TRAPEZIUM", "Trapezium: angles between the parallel sides add to 180°", 4, ["QD_QUAD_ANGLES"], ["WRONG_PAIR_SUPPLEMENTARY"]],
  ["QD_CLASSIFY", "Which family a quadrilateral belongs to", 5, ["QD_SQUARE", "QD_KITE", "QD_TRAPEZIUM"], ["SQUARE_NOT_RECTANGLE", "KITE_AS_PARALLELOGRAM", "ONE_PROPERTY_ENOUGH"]],
], {
  CONCAVE_CONVEX_SWAPPED: "Mixes up convex and concave.",
  COUNTED_SIDES_AS_DIAGONALS: "Counts the sides as diagonals.",
  DOUBLE_COUNTED: "Counts each diagonal twice (forgets to halve n(n − 3)).",
  USED_360: "Uses 360° where the fact is 180°.",
  USED_180: "Uses 180° for a quadrilateral.",
  USED_N_TIMES_180: "Uses n × 180° for the angle sum instead of (n − 2) × 180°.",
  EXTERIOR_SUM_DEPENDS_ON_N: "Thinks the exterior angles add to more for more sides.",
  FORGOT_TO_DIVIDE: "Gives the total angle sum instead of one angle.",
  USED_INTERIOR_AS_EXTERIOR: "Uses the interior angle where the exterior one is needed.",
  DIVIDED_WRONG_WAY: "Divides the angle by 360 instead of 360 by the angle.",
  ADJACENT_SIDES_EQUAL: "Thinks neighbouring sides of a parallelogram are equal.",
  ADJACENT_ANGLES_EQUAL: "Thinks neighbouring angles are equal.",
  OPPOSITE_SUPPLEMENTARY: "Thinks opposite angles add to 180°.",
  DIAGONAL_HALF_MIXED_UP: "Mixes up half a diagonal with the whole diagonal.",
  DIAGONALS_ASSUMED_EQUAL: "Assumes every parallelogram has equal diagonals.",
  NOT_PERPENDICULAR: "Doesn't know a rhombus's diagonals cross at right angles.",
  DIAGONALS_PERPENDICULAR_ASSUMED: "Assumes a rectangle's diagonals cross at right angles.",
  SQUARE_NOT_RECTANGLE: "Thinks a square is not a rectangle (or a rhombus).",
  KITE_AS_PARALLELOGRAM: "Thinks a kite's equal sides are opposite each other.",
  WRONG_PAIR_SUPPLEMENTARY: "Adds the wrong pair of trapezium angles to 180°.",
  ONE_PROPERTY_ENOUGH: "Names a shape from one property when another shape also has it.",
}, [
  ["QD_ANGLE_SUM_TRIANGLE", "NUMBER", "easy", "EXPLORE", "Two angles of a triangle are 65° and 48°. What is the third angle, in degrees?", "67", [], ["USED_360"], "180 - 65 - 48"],
  ["QD_ANGLE_SUM_POLYGON", "NUMBER", "easy", "EXPLORE", "What is the sum of the interior angles of a hexagon, in degrees?", "720", [], ["USED_N_TIMES_180", "USED_360"], "(6 - 2) * 180"],
  ["QD_QUAD_ANGLES", "NUMBER", "easy", "EXPLORE", "Three angles of a quadrilateral are 75°, 90° and 120°. What is the fourth angle, in degrees?", "75", [], ["USED_180"], "360 - 75 - 90 - 120"],
  ["QD_POLYGON_TYPES", "CHOICE", "easy", "EXPLORE", "A polygon has one interior angle bigger than 180°. What kind of polygon is it?", ["Concave", "Convex", "Regular", "It can't be a polygon"], [], ["CONCAVE_CONVEX_SWAPPED"]],
  ["QD_DIAGONALS", "NUMBER", "medium", "EXPLORE", "How many diagonals does a pentagon have?", "5", [], ["COUNTED_SIDES_AS_DIAGONALS", "DOUBLE_COUNTED"], "5 * (5 - 3) / 2"],
  ["QD_EXTERIOR_SUM", "CHOICE", "easy", "EXPLORE", "What do the exterior angles of an octagon add up to?", ["360°", "1080°", "180°", "It depends on the octagon"], [], ["EXTERIOR_SUM_DEPENDS_ON_N"]],
  ["QD_EXTERIOR_REGULAR", "NUMBER", "easy", "EXPLORE", "What is each exterior angle of a regular decagon, in degrees?", "36", [], ["USED_INTERIOR_AS_EXTERIOR"], "360 / 10"],
  ["QD_REGULAR_INTERIOR", "NUMBER", "medium", "EXPLORE", "What is each interior angle of a regular hexagon, in degrees?", "120", ["QD_ANGLE_SUM_POLYGON"], ["FORGOT_TO_DIVIDE", "USED_N_TIMES_180"], "(6 - 2) * 180 / 6"],
  ["QD_INT_EXT_PAIR", "NUMBER", "easy", "EXPLORE", "An interior angle of a polygon is 108°. What is the exterior angle at that corner, in degrees?", "72", [], ["USED_360"], "180 - 108"],
  ["QD_PARALLELOGRAM_ANGLES", "NUMBER", "easy", "EXPLORE", "One angle of a parallelogram is 70°. What is the angle next to it, in degrees?", "110", [], ["ADJACENT_ANGLES_EQUAL"], "180 - 70"],
  ["QD_PARALLELOGRAM_SIDES", "NUMBER", "easy", "EXPLORE", "Two neighbouring sides of a parallelogram are 7 cm and 4 cm. What is its perimeter, in cm?", "22", [], ["ADJACENT_SIDES_EQUAL"], "2 * (7 + 4)"],
  ["QD_PARALLELOGRAM_DIAGONALS", "NUMBER", "medium", "EXPLORE", "The diagonals of parallelogram ABCD meet at O. AC is 16 cm. How long is OA, in cm?", "8", [], ["DIAGONAL_HALF_MIXED_UP"], "16 / 2"],
  ["QD_RHOMBUS", "CHOICE", "medium", "EXPLORE", "At what angle do the diagonals of a rhombus cross?", ["90°", "60°", "180°", "It depends on the rhombus"], [], ["NOT_PERPENDICULAR"]],

  ["QD_EXTERIOR_REGULAR", "NUMBER", "medium", "DIAGNOSE", "Each exterior angle of a regular polygon is 24°. How many sides does it have?", "15", [], ["DIVIDED_WRONG_WAY", "USED_INTERIOR_AS_EXTERIOR"], "360 / 24"],
  ["QD_REGULAR_INTERIOR", "NUMBER", "hard", "DIAGNOSE", "Each interior angle of a regular polygon is 140°. How many sides does it have?", "9", ["QD_INT_EXT_PAIR", "QD_EXTERIOR_REGULAR"], ["USED_INTERIOR_AS_EXTERIOR", "FORGOT_TO_DIVIDE"], "360 / (180 - 140)"],
  ["QD_PARALLELOGRAM_ANGLES", "NUMBER", "medium", "DIAGNOSE", "In a parallelogram, one angle is 30° more than the angle next to it. What is the larger angle, in degrees?", "105", [], ["ADJACENT_ANGLES_EQUAL", "OPPOSITE_SUPPLEMENTARY"], "(180 + 30) / 2"],
  ["QD_QUAD_ANGLES", "NUMBER", "medium", "DIAGNOSE", "The angles of a quadrilateral are in the ratio 3 : 5 : 9 : 13. What is the smallest angle, in degrees?", "36", [], ["USED_180"], "360 * 3 / 30"],
  ["QD_RECTANGLE", "NUMBER", "medium", "DIAGNOSE", "In rectangle PQRS the diagonals meet at O. OP is 6.5 cm. How long is diagonal QS, in cm?", "13", ["QD_PARALLELOGRAM_DIAGONALS"], ["DIAGONAL_HALF_MIXED_UP", "DIAGONALS_PERPENDICULAR_ASSUMED"], "2 * 13/2"],
  ["QD_TRAPEZIUM", "NUMBER", "medium", "DIAGNOSE", "In trapezium ABCD, AB is parallel to DC and angle A is 65°. What is angle D, in degrees?", "115", [], ["WRONG_PAIR_SUPPLEMENTARY"], "180 - 65"],

  ["QD_CLASSIFY", "CHOICE", "medium", "CONFIRM", "Which statement is true?", ["Every square is a rectangle", "Every rectangle is a square", "Every kite is a parallelogram", "Every trapezium is a parallelogram"], [], ["SQUARE_NOT_RECTANGLE", "KITE_AS_PARALLELOGRAM"]],
  ["QD_RHOMBUS", "NUMBER", "hard", "CONFIRM", "The diagonals of a rhombus are 16 cm and 12 cm. How long is each side, in cm?", "10", ["QD_PARALLELOGRAM_DIAGONALS"], ["NOT_PERPENDICULAR", "DIAGONAL_HALF_MIXED_UP"], "x^2 = 8^2 + 6^2"],
  ["QD_ANGLE_SUM_POLYGON", "NUMBER", "hard", "CONFIRM", "Four angles of a pentagon are 100°, 110°, 120° and 95°. What is the fifth angle, in degrees?", "115", [], ["USED_N_TIMES_180", "USED_360"], "(5 - 2) * 180 - 100 - 110 - 120 - 95"],
  ["QD_KITE", "CHOICE", "medium", "CONFIRM", "A kite has two pairs of equal sides. Which sides are equal?", ["Two pairs of neighbouring sides", "Two pairs of opposite sides", "All four sides", "Only one pair"], [], ["KITE_AS_PARALLELOGRAM"]],
  ["QD_CLASSIFY", "CHOICE", "hard", "CONFIRM", "A quadrilateral's diagonals are equal and bisect each other at right angles. What must it be?", ["A square", "A rhombus", "A rectangle", "A kite"], ["QD_SQUARE"], ["ONE_PROPERTY_ENOUGH", "SQUARE_NOT_RECTANGLE"]],
  ["QD_EXTERIOR_REGULAR", "CHOICE", "hard", "CONFIRM", "Can a regular polygon have exterior angles of 22°?", ["No, 360 ÷ 22 is not a whole number", "Yes, it has 22 sides", "Yes, it has about 16 sides", "Yes, any angle is possible"], ["QD_EXTERIOR_SUM"], ["DIVIDED_WRONG_WAY", "EXTERIOR_SUM_DEPENDS_ON_N"]],
]);
