import { draftChapter } from "./draft";

export const CUBES_ROOTS = draftChapter("cubes-roots", 6, [
  ["CB_CUBE", "Cubing a number", 0, [], ["TRIPLED_NOT_CUBED", "SQUARED_NOT_CUBED"]],
  ["CB_PRIME_FACTOR", "Prime factorisation", 0, [], ["NOT_PRIME_FACTORS"]],
  ["CB_PERFECT", "Perfect cubes", 1, ["CB_CUBE"], ["CUBE_AS_SQUARE", "PARTIAL_GROUP_ACCEPTED"]],
  ["CB_UNITS_DIGIT", "Units digit of a cube", 1, ["CB_CUBE"], ["UNITS_DIGIT_NOT_CUBED"]],
  ["CB_NEGATIVE", "Cubes of negative numbers", 1, ["CB_CUBE"], ["NEGATIVE_CUBE_POSITIVE"]],
  ["CB_PATTERNS", "Cube patterns", 2, ["CB_CUBE"], ["PATTERN_MISAPPLIED"]],
  ["CB_ROOT_FACTOR", "Cube root by prime factorisation", 2, ["CB_PRIME_FACTOR", "CB_PERFECT"], ["GROUPED_IN_PAIRS", "TOOK_EVERY_FACTOR"]],
  ["CB_MAKE_PERFECT", "Smallest multiplier or divisor for a perfect cube", 3, ["CB_ROOT_FACTOR"], ["GROUPED_IN_PAIRS", "MULTIPLIED_BY_GROUPED_FACTOR"]],
  ["CB_ROOT_ESTIMATE", "Cube root by grouping digits", 3, ["CB_UNITS_DIGIT"], ["WRONG_GROUPING", "UNITS_DIGIT_NOT_CUBED"]],
  ["CB_FRACTION_ROOT", "Cube roots of fractions and negatives", 3, ["CB_ROOT_FACTOR", "CB_NEGATIVE"], ["ROOTED_ONE_PART", "DROPPED_NEGATIVE"]],
  ["CB_VOLUME", "Cubes as volumes", 4, ["CB_ROOT_FACTOR"], ["USED_SQUARE_ROOT", "DIVIDED_EDGES_ONLY", "ADDED_EDGES"]],
], {
  TRIPLED_NOT_CUBED: "Multiplies by 3 instead of cubing.",
  SQUARED_NOT_CUBED: "Squares instead of cubing.",
  NOT_PRIME_FACTORS: "Leaves a factor that isn't prime.",
  CUBE_AS_SQUARE: "Picks a perfect square as a perfect cube.",
  PARTIAL_GROUP_ACCEPTED: "Calls a number a cube because one of its factors comes in a group of three.",
  UNITS_DIGIT_NOT_CUBED: "Gives the units digit of the number, not of its cube (or the reverse).",
  NEGATIVE_CUBE_POSITIVE: "Thinks the cube of a negative number is positive.",
  PATTERN_MISAPPLIED: "Uses a cube pattern wrongly.",
  GROUPED_IN_PAIRS: "Groups prime factors in twos, as for square roots.",
  TOOK_EVERY_FACTOR: "Multiplies every prime factor instead of one from each group of three.",
  MULTIPLIED_BY_GROUPED_FACTOR: "Multiplies by a factor that is already in a full group of three.",
  WRONG_GROUPING: "Groups the digits from the left instead of in threes from the units place.",
  ROOTED_ONE_PART: "Takes the root of only the top or only the bottom.",
  DROPPED_NEGATIVE: "Gives a positive cube root for a negative number.",
  USED_SQUARE_ROOT: "Takes the square root of a volume instead of the cube root.",
  DIVIDED_EDGES_ONLY: "Divides the edges but doesn't cube the result.",
  ADDED_EDGES: "Adds the edges instead of the volumes.",
}, [
  ["CB_CUBE", "NUMBER", "easy", "EXPLORE", "What is 7³?", "343", [], ["TRIPLED_NOT_CUBED", "SQUARED_NOT_CUBED"], "7^3"],
  ["CB_CUBE", "NUMBER", "easy", "EXPLORE", "What is 15³?", "3375", [], ["SQUARED_NOT_CUBED"], "15^3"],
  ["CB_NEGATIVE", "NUMBER", "easy", "EXPLORE", "What is (−4)³?", "-64", [], ["NEGATIVE_CUBE_POSITIVE"], "(-4)^3"],
  ["CB_UNITS_DIGIT", "NUMBER", "easy", "EXPLORE", "What is the units digit of 23³?", "7", [], ["UNITS_DIGIT_NOT_CUBED"]],
  ["CB_PERFECT", "CHOICE", "easy", "EXPLORE", "Which of these is a perfect cube?", ["216", "100", "144", "250"], [], ["CUBE_AS_SQUARE"]],
  ["CB_PRIME_FACTOR", "CHOICE", "easy", "EXPLORE", "Which is 216 written as a product of primes?", ["2³ × 3³", "6 × 6 × 6", "2³ × 27", "8 × 27"], [], ["NOT_PRIME_FACTORS"]],
  ["CB_ROOT_FACTOR", "NUMBER", "medium", "EXPLORE", "Find the cube root of 3375 by prime factorisation.", "15", [], ["GROUPED_IN_PAIRS", "TOOK_EVERY_FACTOR"], "x^3 = 3375"],
  ["CB_ROOT_FACTOR", "NUMBER", "medium", "EXPLORE", "Find the cube root of 1728.", "12", [], ["GROUPED_IN_PAIRS"], "x^3 = 1728"],
  ["CB_PATTERNS", "NUMBER", "medium", "EXPLORE", "Add 13 + 15 + 17 + 19. The answer is a cube: which number is it?", "64", [], ["PATTERN_MISAPPLIED"], "13 + 15 + 17 + 19"],
  ["CB_FRACTION_ROOT", "NUMBER", "easy", "EXPLORE", "What is the cube root of 8/125?", "2/5", [], ["ROOTED_ONE_PART"], "x^3 = 8/125"],
  ["CB_FRACTION_ROOT", "NUMBER", "medium", "EXPLORE", "What is the cube root of −512?", "-8", ["CB_NEGATIVE"], ["DROPPED_NEGATIVE"], "x^3 = -512"],
  ["CB_ROOT_ESTIMATE", "NUMBER", "medium", "EXPLORE", "Find the cube root of 13824 by grouping its digits.", "24", [], ["WRONG_GROUPING", "UNITS_DIGIT_NOT_CUBED"], "x^3 = 13824"],
  ["CB_VOLUME", "NUMBER", "easy", "EXPLORE", "A cube has a volume of 125 cm³. How long is each edge, in cm?", "5", [], ["USED_SQUARE_ROOT"], "x^3 = 125"],

  ["CB_MAKE_PERFECT", "NUMBER", "medium", "DIAGNOSE", "What is the smallest number you must multiply 392 by to get a perfect cube?", "7", ["CB_PRIME_FACTOR"], ["GROUPED_IN_PAIRS", "MULTIPLIED_BY_GROUPED_FACTOR"]],
  ["CB_MAKE_PERFECT", "NUMBER", "hard", "DIAGNOSE", "What is the smallest number you must divide 81 by to get a perfect cube?", "3", [], ["GROUPED_IN_PAIRS"]],
  ["CB_ROOT_ESTIMATE", "NUMBER", "hard", "DIAGNOSE", "Find the cube root of 175616.", "56", [], ["WRONG_GROUPING", "UNITS_DIGIT_NOT_CUBED"], "x^3 = 175616"],
  ["CB_UNITS_DIGIT", "CHOICE", "medium", "DIAGNOSE", "A number's cube ends in 8. What does the number end in?", ["2", "8", "4", "6"], [], ["UNITS_DIGIT_NOT_CUBED"]],
  ["CB_PERFECT", "CHOICE", "medium", "DIAGNOSE", "Is 500 a perfect cube?", ["No, its 2s don't make a group of three", "Yes, it has 5 × 5 × 5 in it", "Yes, it ends in 0", "No, cubes are always odd"], [], ["PARTIAL_GROUP_ACCEPTED"]],
  ["CB_VOLUME", "NUMBER", "medium", "DIAGNOSE", "How many cubes of edge 3 cm fit exactly into a cube of edge 12 cm?", "64", [], ["DIVIDED_EDGES_ONLY"], "(12 / 3)^3"],

  ["CB_ROOT_FACTOR", "NUMBER", "hard", "CONFIRM", "Find the cube root of 91125.", "45", ["CB_PRIME_FACTOR"], ["GROUPED_IN_PAIRS", "TOOK_EVERY_FACTOR"], "x^3 = 91125"],
  ["CB_FRACTION_ROOT", "NUMBER", "hard", "CONFIRM", "What is the cube root of −27/64?", "-3/4", [], ["DROPPED_NEGATIVE", "ROOTED_ONE_PART"], "x^3 = -27/64"],
  ["CB_MAKE_PERFECT", "NUMBER", "hard", "CONFIRM", "What is the smallest number you must multiply 675 by to get a perfect cube?", "5", [], ["MULTIPLIED_BY_GROUPED_FACTOR", "GROUPED_IN_PAIRS"]],
  ["CB_VOLUME", "NUMBER", "hard", "CONFIRM", "Three cubes with edges 3 cm, 4 cm and 5 cm are melted into one cube. How long is its edge, in cm?", "6", [], ["ADDED_EDGES", "USED_SQUARE_ROOT"], "x^3 = 3^3 + 4^3 + 5^3"],
  ["CB_NEGATIVE", "CHOICE", "medium", "CONFIRM", "Which is true?", ["(−3)³ = −27", "(−3)³ = 27", "(−3)³ = −9", "(−3)³ = 9"], [], ["NEGATIVE_CUBE_POSITIVE"]],
  ["CB_PATTERNS", "CHOICE", "medium", "CONFIRM", "A number ends in 0. How does its cube end?", ["In 000", "In a single 0", "In 00", "In any digit"], [], ["PATTERN_MISAPPLIED"]],
]);
