import { draftChapter } from "./draft";

export const PROPORTIONS = draftChapter("proportions", 11, [
  ["DP_UNITARY", "Unitary method", 0, [], ["DIVIDED_WRONG_WAY"]],
  ["DP_RECOGNISE_DIRECT", "Recognising direct proportion", 1, [], ["ANY_INCREASE_IS_DIRECT"]],
  ["DP_RECOGNISE_INVERSE", "Recognising inverse proportion", 1, [], ["ANY_DECREASE_IS_INVERSE"]],
  ["DP_DIRECT_SOLVE", "Solving direct proportion", 2, ["DP_UNITARY", "DP_RECOGNISE_DIRECT"], ["USED_INVERSE_FOR_DIRECT", "DIFFERENCE_NOT_RATIO"]],
  ["DP_INVERSE_SOLVE", "Solving inverse proportion", 2, ["DP_UNITARY", "DP_RECOGNISE_INVERSE"], ["USED_DIRECT_FOR_INVERSE"]],
  ["DP_TABLE_DIRECT", "Completing a direct-proportion table", 3, ["DP_DIRECT_SOLVE"], ["DIFFERENCE_NOT_RATIO"]],
  ["DP_TABLE_INVERSE", "Completing an inverse-proportion table", 3, ["DP_INVERSE_SOLVE"], ["USED_DIRECT_FOR_INVERSE"]],
  ["DP_SCALE", "Maps and scale drawings", 3, ["DP_DIRECT_SOLVE"], ["UNITS_NOT_CONVERTED", "USED_INVERSE_FOR_DIRECT"]],
  ["DP_WORK", "Workers, taps and days", 4, ["DP_INVERSE_SOLVE"], ["USED_DIRECT_FOR_INVERSE"]],
  ["DP_SPEED_TIME", "Speed and time", 4, ["DP_INVERSE_SOLVE"], ["USED_DIRECT_FOR_INVERSE", "UNITS_NOT_CONVERTED"]],
  ["DP_CHOOSE", "Choosing direct or inverse", 5, ["DP_RECOGNISE_DIRECT", "DP_RECOGNISE_INVERSE"], ["ANY_INCREASE_IS_DIRECT", "ANY_DECREASE_IS_INVERSE"]],
], {
  DIVIDED_WRONG_WAY: "Finds the value of one by dividing the wrong way round.",
  ANY_INCREASE_IS_DIRECT: "Calls two things that both increase directly proportional, even without a fixed ratio.",
  ANY_DECREASE_IS_INVERSE: "Calls any pair where one goes down inversely proportional.",
  USED_INVERSE_FOR_DIRECT: "Multiplies across (inverse) when the quantities are directly proportional.",
  DIFFERENCE_NOT_RATIO: "Adds the same amount instead of keeping the same ratio.",
  USED_DIRECT_FOR_INVERSE: "Scales up (direct) when the quantities are inversely proportional.",
  UNITS_NOT_CONVERTED: "Leaves the answer in the wrong units (cm instead of m or km).",
}, [
  ["DP_UNITARY", "NUMBER", "easy", "EXPLORE", "5 pens cost ₹60. What do 8 pens cost, in ₹?", "96", [], ["DIVIDED_WRONG_WAY"], "60 / 5 * 8"],
  ["DP_RECOGNISE_DIRECT", "CHOICE", "easy", "EXPLORE", "Which pair is in direct proportion?", ["Kilograms of rice and its cost", "Speed and time for the same trip", "Workers and days for the same job", "A child's age and height"], [], ["ANY_INCREASE_IS_DIRECT"]],
  ["DP_RECOGNISE_INVERSE", "CHOICE", "easy", "EXPLORE", "Which pair is in inverse proportion?", ["Number of taps and time to fill a tank", "Distance driven and petrol used", "Hours worked and wages", "Side of a square and its perimeter"], [], ["ANY_DECREASE_IS_INVERSE"]],
  ["DP_DIRECT_SOLVE", "NUMBER", "easy", "EXPLORE", "A car uses 6 litres of petrol for 90 km. How many litres does it use for 150 km?", "10", [], ["USED_INVERSE_FOR_DIRECT"], "6 / 90 * 150"],
  ["DP_INVERSE_SOLVE", "NUMBER", "easy", "EXPLORE", "6 workers build a wall in 10 days. How many days would 4 workers take?", "15", [], ["USED_DIRECT_FOR_INVERSE"], "6 * 10 / 4"],
  ["DP_TABLE_DIRECT", "NUMBER", "medium", "EXPLORE", "x and y are in direct proportion. When x = 4, y = 14. What is y when x = 10?", "35", [], ["DIFFERENCE_NOT_RATIO"], "14 / 4 * 10"],
  ["DP_TABLE_INVERSE", "NUMBER", "medium", "EXPLORE", "x and y are in inverse proportion. When x = 6, y = 20. What is y when x = 8?", "15", [], ["USED_DIRECT_FOR_INVERSE"], "6 * 20 / 8"],
  ["DP_SCALE", "NUMBER", "medium", "EXPLORE", "On a map, 1 cm stands for 5 km. Two towns are 7.5 cm apart on the map. How far apart are they, in km?", "37.5", [], ["USED_INVERSE_FOR_DIRECT"], "15/2 * 5"],
  ["DP_SPEED_TIME", "NUMBER", "medium", "EXPLORE", "At 60 km/h a trip takes 4 hours. How long does it take at 80 km/h, in hours?", "3", [], ["USED_DIRECT_FOR_INVERSE"], "60 * 4 / 80"],
  ["DP_WORK", "NUMBER", "medium", "EXPLORE", "A store of food lasts 150 students for 20 days. How long would it last 100 students, in days?", "30", [], ["USED_DIRECT_FOR_INVERSE"], "20 * 150 / 100"],
  ["DP_DIRECT_SOLVE", "NUMBER", "medium", "EXPLORE", "A machine makes 840 bottles in 6 hours. How many does it make in 5 hours?", "700", [], ["USED_INVERSE_FOR_DIRECT", "DIFFERENCE_NOT_RATIO"], "840 / 6 * 5"],
  ["DP_UNITARY", "NUMBER", "easy", "EXPLORE", "12 identical books weigh 4.8 kg. How much do 5 of them weigh, in kg?", "2", [], ["DIVIDED_WRONG_WAY"], "48/10 / 12 * 5"],
  ["DP_CHOOSE", "CHOICE", "medium", "EXPLORE", "More pipes fill a tank faster. Are the number of pipes and the time taken in direct or inverse proportion?", ["Inverse: more pipes, less time", "Direct: both are about the tank", "Direct: more pipes, more water", "Neither"], [], ["ANY_INCREASE_IS_DIRECT"]],

  ["DP_TABLE_DIRECT", "NUMBER", "medium", "DIAGNOSE", "x and y are in direct proportion: x = 3 gives y = 12 and x = 5 gives y = 20. What is y when x = 9?", "36", [], ["DIFFERENCE_NOT_RATIO"], "12 / 3 * 9"],
  ["DP_SCALE", "NUMBER", "hard", "DIAGNOSE", "A model ship is built at a scale of 1 : 200. The model is 45 cm long. How long is the real ship, in m?", "90", [], ["UNITS_NOT_CONVERTED"], "45 * 200 / 100"],
  ["DP_WORK", "NUMBER", "hard", "DIAGNOSE", "15 workers can finish a job in 48 hours. How many workers are needed to finish it in 30 hours?", "24", [], ["USED_DIRECT_FOR_INVERSE"], "15 * 48 / 30"],
  ["DP_SPEED_TIME", "NUMBER", "hard", "DIAGNOSE", "A train at 75 km/h covers a distance in 2 hours. How fast must it go to cover it in 1.5 hours, in km/h?", "100", [], ["USED_DIRECT_FOR_INVERSE"], "75 * 2 / (3/2)"],
  ["DP_CHOOSE", "CHOICE", "medium", "DIAGNOSE", "As a child grows older, they get taller. Are age and height in direct proportion?", ["No, height doesn't grow in a fixed ratio to age", "Yes, both increase", "No, they are in inverse proportion", "Yes, height doubles when age doubles"], [], ["ANY_INCREASE_IS_DIRECT"]],
  ["DP_INVERSE_SOLVE", "NUMBER", "medium", "DIAGNOSE", "A packet of sweets gives 24 children 5 sweets each. How many would each child get if it were shared among 20 children?", "6", [], ["USED_DIRECT_FOR_INVERSE"], "24 * 5 / 20"],

  ["DP_WORK", "NUMBER", "hard", "CONFIRM", "8 taps fill a tank in 27 minutes. If 2 taps stop working, how long does the tank take to fill, in minutes?", "36", [], ["USED_DIRECT_FOR_INVERSE"], "8 * 27 / 6"],
  ["DP_DIRECT_SOLVE", "NUMBER", "hard", "CONFIRM", "A 14 m pole casts a 10 m shadow. At the same time, a tree casts a 15 m shadow. How tall is the tree, in m?", "21", [], ["USED_INVERSE_FOR_DIRECT"], "14 / 10 * 15"],
  ["DP_TABLE_INVERSE", "NUMBER", "hard", "CONFIRM", "x and y are in inverse proportion: x = 2 gives y = 36. What is x when y = 9?", "8", [], ["USED_DIRECT_FOR_INVERSE"], "2 * 36 / 9"],
  ["DP_SPEED_TIME", "NUMBER", "hard", "CONFIRM", "A cyclist takes 45 minutes at 12 km/h. How long does the same ride take at 18 km/h, in minutes?", "30", [], ["USED_DIRECT_FOR_INVERSE"], "45 * 12 / 18"],
  ["DP_SCALE", "NUMBER", "medium", "CONFIRM", "On a map, 2 cm shows 15 km. How many cm show 60 km?", "8", [], ["USED_INVERSE_FOR_DIRECT"], "2 / 15 * 60"],
  ["DP_WORK", "NUMBER", "hard", "CONFIRM", "10 workers can do a job in 12 days. After 4 days, 2 workers leave. How many more days does the rest of the job take?", "10", [], ["USED_DIRECT_FOR_INVERSE"], "10 * (12 - 4) / 8"],
]);
