import { draftChapter } from "./draft";

export const RATIONAL_NUMBERS = draftChapter("rational-numbers", 1, [
  ["RN_WHAT_IS", "What a rational number is", 0, [], ["ZERO_DENOMINATOR_ALLOWED", "INTEGER_NOT_RATIONAL"]],
  ["RN_SIGNED_INT", "Adding and multiplying integers", 0, [], ["SIGN_SUM_ERROR", "SIGN_PRODUCT_ERROR"]],
  ["RN_EQUIV_FRACTION", "Equivalent fractions", 0, [], ["CHANGED_ONE_PART_ONLY"]],
  ["RN_STANDARD_FORM", "Lowest terms with a positive denominator", 1, ["RN_EQUIV_FRACTION", "RN_SIGNED_INT"], ["NOT_FULLY_REDUCED", "NEGATIVE_DENOMINATOR_LEFT"]],
  ["RN_COMPARE", "Comparing rational numbers", 1, ["RN_EQUIV_FRACTION"], ["COMPARED_DENOMINATORS", "NEGATIVE_ORDER_FLIPPED"]],
  ["RN_NUMBER_LINE", "Rational numbers on the number line", 1, ["RN_COMPARE"], ["COUNTED_WRONG_DIRECTION"]],
  ["RN_ADD_INVERSE", "Additive inverse", 1, ["RN_SIGNED_INT"], ["GAVE_RECIPROCAL"]],
  ["RN_ADD_SAME", "Adding with the same denominator", 2, ["RN_SIGNED_INT"], ["ADDED_DENOMINATORS"]],
  ["RN_ADD_DIFF", "Adding with different denominators", 2, ["RN_ADD_SAME", "RN_EQUIV_FRACTION"], ["ADDED_DENOMINATORS", "NUMERATOR_NOT_SCALED"]],
  ["RN_SUBTRACT", "Subtracting rational numbers", 2, ["RN_ADD_DIFF"], ["SUBTRACTED_WRONG_WAY", "NEGATIVE_NOT_ADDED"]],
  ["RN_MULTIPLY", "Multiplying rational numbers", 2, ["RN_SIGNED_INT"], ["CROSS_MULTIPLIED", "SIGN_PRODUCT_ERROR"]],
  ["RN_RECIPROCAL", "Reciprocals", 2, ["RN_WHAT_IS"], ["RECIPROCAL_SIGN_FLIPPED", "NEGATED_INSTEAD", "ZERO_HAS_RECIPROCAL"]],
  ["RN_DIVIDE", "Dividing rational numbers", 3, ["RN_MULTIPLY", "RN_RECIPROCAL"], ["FLIPPED_FIRST", "NOT_FLIPPED"]],
  ["RN_IDENTITY", "0 and 1 as identities", 3, [], ["ZERO_AS_MULT_IDENTITY"]],
  ["RN_PROPERTIES", "Commutative and associative properties", 3, ["RN_ADD_DIFF", "RN_MULTIPLY"], ["SUBTRACTION_COMMUTATIVE", "DIVISION_ASSOCIATIVE"]],
  ["RN_DISTRIBUTIVE", "Distributing multiplication over addition", 3, ["RN_MULTIPLY", "RN_ADD_DIFF"], ["MULTIPLIED_FIRST_TERM_ONLY"]],
  ["RN_BETWEEN", "Rational numbers between two others", 4, ["RN_COMPARE", "RN_ADD_DIFF"], ["THINKS_NONE_BETWEEN", "OUTSIDE_INTERVAL"]],
  ["RN_WORD", "Fraction word problems", 4, ["RN_ADD_DIFF", "RN_MULTIPLY"], ["WRONG_OPERATION"]],
], {
  ZERO_DENOMINATOR_ALLOWED: "Accepts a fraction with 0 as the denominator.",
  INTEGER_NOT_RATIONAL: "Thinks whole numbers and integers are not rational.",
  SIGN_SUM_ERROR: "Gets the sign wrong when adding a positive and a negative.",
  SIGN_PRODUCT_ERROR: "Gets the sign of a product or quotient wrong.",
  CHANGED_ONE_PART_ONLY: "Multiplies only the top or only the bottom to make an equivalent fraction.",
  NOT_FULLY_REDUCED: "Stops before the fraction is in lowest terms.",
  NEGATIVE_DENOMINATOR_LEFT: "Leaves the minus sign in the denominator.",
  COMPARED_DENOMINATORS: "Compares fractions by their denominators alone.",
  NEGATIVE_ORDER_FLIPPED: "Thinks −5/6 > −3/4 because 5/6 > 3/4.",
  COUNTED_WRONG_DIRECTION: "Places a negative number on the positive side, or counts parts the wrong way.",
  GAVE_RECIPROCAL: "Gives the reciprocal when asked for the additive inverse.",
  ADDED_DENOMINATORS: "Adds the tops and adds the bottoms.",
  NUMERATOR_NOT_SCALED: "Changes the denominator to the LCM but leaves the numerator as it was.",
  SUBTRACTED_WRONG_WAY: "Subtracts in the wrong order.",
  NEGATIVE_NOT_ADDED: "Treats subtracting a negative as subtracting.",
  CROSS_MULTIPLIED: "Cross-multiplies when multiplying two fractions.",
  RECIPROCAL_SIGN_FLIPPED: "Flips the fraction and also changes its sign.",
  NEGATED_INSTEAD: "Changes the sign instead of flipping the fraction.",
  ZERO_HAS_RECIPROCAL: "Thinks 0 has a reciprocal.",
  FLIPPED_FIRST: "Flips the first fraction instead of the divisor.",
  NOT_FLIPPED: "Multiplies by the divisor without flipping it.",
  ZERO_AS_MULT_IDENTITY: "Thinks 0 is the identity for multiplication.",
  SUBTRACTION_COMMUTATIVE: "Thinks a − b = b − a.",
  DIVISION_ASSOCIATIVE: "Thinks division or subtraction can be regrouped freely.",
  MULTIPLIED_FIRST_TERM_ONLY: "Multiplies only the first number in the bracket.",
  THINKS_NONE_BETWEEN: "Thinks there are no (or only a few) rational numbers between two close ones.",
  OUTSIDE_INTERVAL: "Picks a number that is not actually between the two.",
  WRONG_OPERATION: "Uses the wrong operation for the story.",
}, [
  ["RN_ADD_SAME", "NUMBER", "easy", "EXPLORE", "Work out −3/7 + 5/7.", "2/7", [], ["ADDED_DENOMINATORS"], "-3/7 + 5/7"],
  ["RN_ADD_DIFF", "NUMBER", "easy", "EXPLORE", "Work out 2/3 + 1/4.", "11/12", [], ["ADDED_DENOMINATORS", "NUMERATOR_NOT_SCALED"], "2/3 + 1/4"],
  ["RN_ADD_DIFF", "NUMBER", "medium", "EXPLORE", "Work out −5/6 + 3/4.", "-1/12", ["RN_SIGNED_INT"], ["NUMERATOR_NOT_SCALED", "SIGN_SUM_ERROR"], "-5/6 + 3/4"],
  ["RN_SUBTRACT", "NUMBER", "medium", "EXPLORE", "Work out 3/5 − (−2/3).", "19/15", ["RN_ADD_DIFF"], ["NEGATIVE_NOT_ADDED", "ADDED_DENOMINATORS"], "3/5 - (-2/3)"],
  ["RN_MULTIPLY", "NUMBER", "easy", "EXPLORE", "Work out −3/4 × 2/9 in lowest terms.", "-1/6", ["RN_STANDARD_FORM"], ["CROSS_MULTIPLIED", "NOT_FULLY_REDUCED"], "-3/4 * 2/9"],
  ["RN_RECIPROCAL", "CHOICE", "easy", "EXPLORE", "What is the reciprocal of −5/8?", ["−8/5", "8/5", "5/8", "−5/8"], [], ["RECIPROCAL_SIGN_FLIPPED", "NEGATED_INSTEAD"]],
  ["RN_DIVIDE", "NUMBER", "medium", "EXPLORE", "Work out −7/8 ÷ 14/3 in lowest terms.", "-3/16", ["RN_RECIPROCAL", "RN_MULTIPLY"], ["FLIPPED_FIRST", "NOT_FLIPPED"], "(-7/8) / (14/3)"],
  ["RN_STANDARD_FORM", "NUMBER", "easy", "EXPLORE", "Write 36/−48 in standard form.", "-3/4", [], ["NOT_FULLY_REDUCED", "NEGATIVE_DENOMINATOR_LEFT"], "36/(-48)"],
  ["RN_COMPARE", "CHOICE", "medium", "EXPLORE", "Which is greater: −3/4 or −5/6?", ["−3/4", "−5/6", "They are equal", "You can't compare negatives"], [], ["NEGATIVE_ORDER_FLIPPED", "COMPARED_DENOMINATORS"]],
  ["RN_ADD_INVERSE", "CHOICE", "easy", "EXPLORE", "What is the additive inverse of −2/9?", ["2/9", "−9/2", "9/2", "−2/9"], [], ["GAVE_RECIPROCAL"]],
  ["RN_WHAT_IS", "CHOICE", "easy", "EXPLORE", "Which of these is not a rational number?", ["3/0", "0", "−7", "5/−2"], [], ["ZERO_DENOMINATOR_ALLOWED", "INTEGER_NOT_RATIONAL"]],
  ["RN_NUMBER_LINE", "CHOICE", "medium", "EXPLORE", "On the number line, −7/4 lies between which two integers?", ["−2 and −1", "1 and 2", "−1 and 0", "−7 and −4"], ["RN_COMPARE"], ["COUNTED_WRONG_DIRECTION"]],
  ["RN_IDENTITY", "CHOICE", "easy", "EXPLORE", "Which number can you multiply any rational number by and leave it unchanged?", ["1", "0", "−1", "There is no such number"], [], ["ZERO_AS_MULT_IDENTITY"]],

  ["RN_PROPERTIES", "CHOICE", "medium", "DIAGNOSE", "Is 2/3 − 1/5 equal to 1/5 − 2/3?", ["No, one is the negative of the other", "Yes, subtraction can be done in any order", "Yes, both are 7/15", "Only if you use the LCM"], ["RN_SUBTRACT"], ["SUBTRACTION_COMMUTATIVE"]],
  ["RN_DISTRIBUTIVE", "NUMBER", "medium", "DIAGNOSE", "Use the distributive property to work out 3/7 × (14/9 + 7/3).", "5/3", ["RN_MULTIPLY"], ["MULTIPLIED_FIRST_TERM_ONLY"], "3/7 * (14/9 + 7/3)"],
  ["RN_SUBTRACT", "NUMBER", "hard", "DIAGNOSE", "Work out −2/5 − 7/10 − (−1/2) in lowest terms.", "-3/5", ["RN_ADD_DIFF", "RN_STANDARD_FORM"], ["NEGATIVE_NOT_ADDED", "SUBTRACTED_WRONG_WAY"], "-2/5 - 7/10 - (-1/2)"],
  ["RN_DIVIDE", "NUMBER", "hard", "DIAGNOSE", "Work out (−5/12) ÷ (−15/8) in lowest terms.", "2/9", ["RN_SIGNED_INT", "RN_STANDARD_FORM"], ["NOT_FLIPPED", "SIGN_PRODUCT_ERROR"], "(-5/12) / (-15/8)"],
  ["RN_BETWEEN", "CHOICE", "medium", "DIAGNOSE", "Which number lies between 1/3 and 1/2?", ["5/12", "1/4", "2/3", "3/5"], ["RN_COMPARE"], ["OUTSIDE_INTERVAL"]],
  ["RN_WORD", "NUMBER", "medium", "DIAGNOSE", "Ravi walks 3/4 km to school and then 2/5 km more to the library. How far does he walk in all, in km?", "23/20", ["RN_ADD_DIFF"], ["WRONG_OPERATION", "ADDED_DENOMINATORS"], "3/4 + 2/5"],

  ["RN_PROPERTIES", "CHOICE", "medium", "CONFIRM", "Which operation on rational numbers gives the same answer in either order?", ["Multiplication", "Subtraction", "Division", "None of these"], [], ["SUBTRACTION_COMMUTATIVE", "DIVISION_ASSOCIATIVE"]],
  ["RN_BETWEEN", "CHOICE", "hard", "CONFIRM", "How many rational numbers lie between −1/2 and −1/3?", ["As many as you like (infinitely many)", "None", "Exactly one", "Exactly five"], [], ["THINKS_NONE_BETWEEN"]],
  ["RN_DISTRIBUTIVE", "NUMBER", "hard", "CONFIRM", "Work out −2/5 × 3/7 + 1/14 − 3/7 × 3/5.", "-5/14", ["RN_ADD_DIFF", "RN_PROPERTIES"], ["MULTIPLIED_FIRST_TERM_ONLY", "NUMERATOR_NOT_SCALED"], "-2/5 * 3/7 + 1/14 - 3/7 * 3/5"],
  ["RN_WORD", "NUMBER", "hard", "CONFIRM", "A tank is 5/8 full. Then 1/4 of a full tank of water is used. What fraction of the tank is full now?", "3/8", ["RN_SUBTRACT"], ["WRONG_OPERATION"], "5/8 - 1/4"],
  ["RN_MULTIPLY", "NUMBER", "medium", "CONFIRM", "Work out (−4/9) × (−27/16) in lowest terms.", "3/4", ["RN_STANDARD_FORM", "RN_SIGNED_INT"], ["SIGN_PRODUCT_ERROR", "NOT_FULLY_REDUCED"], "(-4/9) * (-27/16)"],
  ["RN_RECIPROCAL", "CHOICE", "medium", "CONFIRM", "Which number has no reciprocal?", ["0", "1", "−1", "1/2"], [], ["ZERO_HAS_RECIPROCAL"]],
]);
