import { draftChapter } from "./draft";

export const COMPARING_QUANTITIES = draftChapter("comparing-quantities", 7, [
  ["CQ_RATIO", "Ratios", 0, [], ["RATIO_REVERSED", "UNITS_NOT_MATCHED"]],
  ["CQ_PERCENT_CONVERT", "Fractions, decimals and percentages", 0, [], ["PERCENT_NOT_OVER_100"]],
  ["CQ_PERCENT_OF", "Percentage of a quantity", 1, ["CQ_PERCENT_CONVERT"], ["DIVIDED_BY_PERCENT"]],
  ["CQ_PERCENT_CHANGE", "Percentage increase and decrease", 2, ["CQ_PERCENT_OF"], ["CHANGE_OVER_NEW_VALUE", "GAVE_CHANGE_NOT_PERCENT"]],
  ["CQ_SIMPLE_INTEREST", "Simple interest", 2, ["CQ_PERCENT_OF"], ["FORGOT_TIME"]],
  ["CQ_DISCOUNT", "Discount", 3, ["CQ_PERCENT_OF"], ["DISCOUNT_ON_SALE_PRICE", "GAVE_DISCOUNT_NOT_PRICE"]],
  ["CQ_PROFIT_LOSS", "Profit and loss", 3, ["CQ_PERCENT_CHANGE"], ["PROFIT_OVER_SP", "LOSS_ADDED"]],
  ["CQ_GST", "Sales tax and GST", 3, ["CQ_PERCENT_OF"], ["GAVE_TAX_NOT_TOTAL", "TAX_SUBTRACTED", "TAX_TAKEN_ON_TOTAL"]],
  ["CQ_COST_PRICE", "Finding the cost price from a profit", 4, ["CQ_PROFIT_LOSS"], ["PERCENT_OF_SP_SUBTRACTED"]],
  ["CQ_SUCCESSIVE", "Successive percentage changes", 4, ["CQ_PERCENT_CHANGE"], ["ADDED_PERCENTAGES"]],
  ["CQ_COMPOUND_INTEREST", "Compound interest", 4, ["CQ_SIMPLE_INTEREST"], ["USED_SIMPLE_INTEREST", "GAVE_AMOUNT_NOT_INTEREST"]],
  ["CQ_HALF_YEARLY", "Compounding half-yearly", 5, ["CQ_COMPOUND_INTEREST"], ["RATE_NOT_HALVED", "PERIODS_NOT_DOUBLED"]],
  ["CQ_GROWTH", "Growth and depreciation", 5, ["CQ_COMPOUND_INTEREST"], ["DEPRECIATION_ADDED"]],
], {
  RATIO_REVERSED: "Writes the ratio, or shares the amount, the wrong way round.",
  UNITS_NOT_MATCHED: "Compares quantities in different units (minutes with hours).",
  PERCENT_NOT_OVER_100: "Forgets that per cent means out of 100.",
  DIVIDED_BY_PERCENT: "Divides by the percentage instead of multiplying by it over 100.",
  CHANGE_OVER_NEW_VALUE: "Divides the change by the new value instead of the original.",
  GAVE_CHANGE_NOT_PERCENT: "Gives the amount of change, not the percentage.",
  FORGOT_TIME: "Leaves the number of years out of simple interest.",
  DISCOUNT_ON_SALE_PRICE: "Works out the discount on the sale price instead of the marked price.",
  GAVE_DISCOUNT_NOT_PRICE: "Gives the discount when the question asks for the price.",
  PROFIT_OVER_SP: "Divides the profit by the selling price instead of the cost price.",
  LOSS_ADDED: "Adds a loss to the cost price.",
  GAVE_TAX_NOT_TOTAL: "Gives only the tax when the question asks for the total.",
  TAX_SUBTRACTED: "Takes the tax away instead of adding it.",
  TAX_TAKEN_ON_TOTAL: "Takes the tax percentage of a price that already includes tax.",
  PERCENT_OF_SP_SUBTRACTED: "Takes the profit percentage of the selling price and subtracts it.",
  ADDED_PERCENTAGES: "Adds successive percentages instead of applying one after the other.",
  USED_SIMPLE_INTEREST: "Uses simple interest when the interest is compounded.",
  GAVE_AMOUNT_NOT_INTEREST: "Gives the amount when the question asks for the interest.",
  RATE_NOT_HALVED: "Uses the yearly rate for each half-year.",
  PERIODS_NOT_DOUBLED: "Counts years instead of half-years.",
  DEPRECIATION_ADDED: "Adds the percentage when the value falls.",
}, [
  ["CQ_RATIO", "CHOICE", "easy", "EXPLORE", "What is the ratio of 45 minutes to 1 hour, in simplest form?", ["3 : 4", "45 : 1", "4 : 3", "3 : 40"], [], ["UNITS_NOT_MATCHED", "RATIO_REVERSED"]],
  ["CQ_PERCENT_CONVERT", "NUMBER", "easy", "EXPLORE", "Write 3/8 as a percentage.", "37.5", [], ["PERCENT_NOT_OVER_100"], "3/8 * 100"],
  ["CQ_PERCENT_OF", "NUMBER", "easy", "EXPLORE", "What is 15% of 240?", "36", [], ["DIVIDED_BY_PERCENT"], "15/100 * 240"],
  ["CQ_PERCENT_CHANGE", "NUMBER", "easy", "EXPLORE", "A price rises from ₹80 to ₹100. What is the percentage increase?", "25", [], ["CHANGE_OVER_NEW_VALUE", "GAVE_CHANGE_NOT_PERCENT"], "(100 - 80) / 80 * 100"],
  ["CQ_PERCENT_CHANGE", "NUMBER", "medium", "EXPLORE", "A school's roll falls from 1250 students to 1000. What is the percentage decrease?", "20", [], ["CHANGE_OVER_NEW_VALUE"], "(1250 - 1000) / 1250 * 100"],
  ["CQ_DISCOUNT", "NUMBER", "easy", "EXPLORE", "A shirt marked ₹600 has a 20% discount. What is the sale price, in ₹?", "480", [], ["GAVE_DISCOUNT_NOT_PRICE"], "600 - 20/100 * 600"],
  ["CQ_DISCOUNT", "NUMBER", "medium", "EXPLORE", "A bag marked ₹1500 sells for ₹1275. What is the discount percent?", "15", [], ["DISCOUNT_ON_SALE_PRICE"], "(1500 - 1275) / 1500 * 100"],
  ["CQ_PROFIT_LOSS", "NUMBER", "easy", "EXPLORE", "A book bought for ₹250 is sold for ₹300. What is the profit percent?", "20", [], ["PROFIT_OVER_SP"], "(300 - 250) / 250 * 100"],
  ["CQ_GST", "NUMBER", "easy", "EXPLORE", "A phone costs ₹8000 plus 18% GST. What is the total price, in ₹?", "9440", [], ["GAVE_TAX_NOT_TOTAL", "TAX_SUBTRACTED"], "8000 + 18/100 * 8000"],
  ["CQ_SIMPLE_INTEREST", "NUMBER", "easy", "EXPLORE", "Find the simple interest on ₹5000 at 8% a year for 3 years, in ₹.", "1200", [], ["FORGOT_TIME"], "5000 * 8 * 3 / 100"],
  ["CQ_COMPOUND_INTEREST", "NUMBER", "medium", "EXPLORE", "Find the amount on ₹10000 at 10% a year, compounded yearly, after 2 years, in ₹.", "12100", [], ["USED_SIMPLE_INTEREST"], "10000 * (1 + 10/100)^2"],
  ["CQ_COMPOUND_INTEREST", "NUMBER", "medium", "EXPLORE", "Find the compound interest on ₹8000 at 5% a year for 2 years, in ₹.", "820", [], ["GAVE_AMOUNT_NOT_INTEREST", "USED_SIMPLE_INTEREST"], "8000 * (1 + 5/100)^2 - 8000"],
  ["CQ_PERCENT_CONVERT", "CHOICE", "easy", "EXPLORE", "Which is the same as 0.05?", ["5%", "50%", "0.5%", "0.05%"], [], ["PERCENT_NOT_OVER_100"]],

  ["CQ_COST_PRICE", "NUMBER", "hard", "DIAGNOSE", "A table is sold for ₹2400 at a profit of 20%. What was its cost price, in ₹?", "2000", [], ["PERCENT_OF_SP_SUBTRACTED"], "x + 20/100 * x = 2400"],
  ["CQ_GST", "NUMBER", "hard", "DIAGNOSE", "A price including 12% GST is ₹1120. What was the price before GST, in ₹?", "1000", [], ["TAX_TAKEN_ON_TOTAL"], "x * 112/100 = 1120"],
  ["CQ_SUCCESSIVE", "NUMBER", "hard", "DIAGNOSE", "A price goes up by 10% and then down by 10%. What is the overall percentage change? (Use a minus sign for a decrease.)", "-1", [], ["ADDED_PERCENTAGES"], "(110/100 * 90/100 - 1) * 100"],
  ["CQ_HALF_YEARLY", "NUMBER", "hard", "DIAGNOSE", "Find the amount on ₹4000 at 10% a year for 1 year, compounded half-yearly, in ₹.", "4410", [], ["RATE_NOT_HALVED", "PERIODS_NOT_DOUBLED"], "4000 * (1 + 5/100)^2"],
  ["CQ_GROWTH", "NUMBER", "medium", "DIAGNOSE", "A scooter worth ₹40000 loses 10% of its value each year. What is it worth after 2 years, in ₹?", "32400", [], ["DEPRECIATION_ADDED"], "40000 * (1 - 10/100)^2"],
  ["CQ_PROFIT_LOSS", "NUMBER", "medium", "DIAGNOSE", "A fan bought for ₹1200 is sold at a loss of 15%. What is the selling price, in ₹?", "1020", [], ["LOSS_ADDED"], "1200 - 15/100 * 1200"],

  ["CQ_DISCOUNT", "NUMBER", "hard", "CONFIRM", "After a 25% discount, a jacket costs ₹1800. What was its marked price, in ₹?", "2400", [], ["DISCOUNT_ON_SALE_PRICE"], "x - 25/100 * x = 1800"],
  ["CQ_COMPOUND_INTEREST", "NUMBER", "hard", "CONFIRM", "Find the compound interest on ₹12000 at 10% a year for 3 years, in ₹.", "3972", [], ["USED_SIMPLE_INTEREST", "GAVE_AMOUNT_NOT_INTEREST"], "12000 * (11/10)^3 - 12000"],
  ["CQ_GROWTH", "NUMBER", "hard", "CONFIRM", "A town of 20000 people grows by 5% a year. What is its population after 2 years?", "22050", ["CQ_COMPOUND_INTEREST"], ["USED_SIMPLE_INTEREST"], "20000 * (1 + 5/100)^2"],
  ["CQ_PERCENT_OF", "NUMBER", "medium", "CONFIRM", "72% of a school's students are girls, and there are 350 boys. How many students are there?", "1250", [], ["DIVIDED_BY_PERCENT"], "28/100 * x = 350"],
  ["CQ_SUCCESSIVE", "NUMBER", "hard", "CONFIRM", "A shop takes 20% off, then another 10% off the reduced price. What single discount percent is that the same as?", "28", [], ["ADDED_PERCENTAGES"], "(1 - 80/100 * 90/100) * 100"],
  ["CQ_RATIO", "NUMBER", "medium", "CONFIRM", "₹720 is shared between Ali and Bina in the ratio 5 : 3. How much does Ali get, in ₹?", "450", [], ["RATIO_REVERSED"], "720 * 5/8"],
]);
