import { draftChapter } from "./draft";

/** Shapes are described in words and π is given as 22/7, so every answer is an exact number. */
export const MENSURATION = draftChapter("mensuration", 9, [
  ["MN_RECT_AREA", "Area of rectangles and squares", 0, [], ["PERIMETER_FOR_AREA"]],
  ["MN_TRIANGLE_AREA", "Area of a triangle", 0, [], ["FORGOT_HALF"]],
  ["MN_CIRCLE", "Circumference and area of a circle", 0, [], ["DIAMETER_AS_RADIUS", "AREA_CIRCUMFERENCE_SWAPPED"]],
  ["MN_PARALLELOGRAM_AREA", "Area of a parallelogram", 1, ["MN_RECT_AREA"], ["SLANT_AS_HEIGHT"]],
  ["MN_TRAPEZIUM", "Area of a trapezium", 2, ["MN_TRIANGLE_AREA"], ["FORGOT_HALF", "ADDED_ALL_SIDES"]],
  ["MN_RHOMBUS", "Area of a rhombus from its diagonals", 2, ["MN_TRIANGLE_AREA"], ["FORGOT_HALF"]],
  ["MN_POLYGON_SPLIT", "Area of a shape by splitting it", 3, ["MN_TRAPEZIUM"], ["PIECE_MISSED"]],
  ["MN_CUBOID_SA", "Surface area of a cuboid", 3, ["MN_RECT_AREA"], ["ONE_OF_EACH_FACE", "USED_VOLUME"]],
  ["MN_CUBE_SA", "Surface area of a cube", 3, ["MN_CUBOID_SA"], ["FOUR_FACES_ONLY"]],
  ["MN_LATERAL", "Area of the four walls", 3, ["MN_CUBOID_SA"], ["INCLUDED_TOP_BOTTOM"]],
  ["MN_VOLUME_CUBOID", "Volume of a cuboid and a cube", 3, ["MN_RECT_AREA"], ["ADDED_DIMENSIONS", "SCALED_LINEARLY"]],
  ["MN_CYLINDER_SA", "Surface area of a cylinder", 4, ["MN_CIRCLE"], ["ONE_END_ONLY", "DIAMETER_AS_RADIUS", "ADDED_ENDS_TO_CURVED"]],
  ["MN_VOLUME_CYLINDER", "Volume of a cylinder", 4, ["MN_CIRCLE", "MN_VOLUME_CUBOID"], ["USED_DIAMETER", "USED_CIRCUMFERENCE"]],
  ["MN_UNITS", "cm³, m³ and litres", 4, ["MN_VOLUME_CUBOID"], ["LITRE_CONVERSION_WRONG"]],
  ["MN_FIND_DIMENSION", "Finding a missing length from an area or volume", 5, ["MN_VOLUME_CUBOID"], ["WRONG_OPERATION"]],
], {
  PERIMETER_FOR_AREA: "Adds the sides (perimeter) when the question asks for area.",
  FORGOT_HALF: "Leaves out the ½.",
  DIAMETER_AS_RADIUS: "Uses the diameter where the formula needs the radius.",
  AREA_CIRCUMFERENCE_SWAPPED: "Uses 2πr for area or πr² for circumference.",
  SLANT_AS_HEIGHT: "Uses the slanted side as the height.",
  ADDED_ALL_SIDES: "Adds all four sides of the trapezium instead of the two parallel ones.",
  PIECE_MISSED: "Leaves one piece of the shape out.",
  ONE_OF_EACH_FACE: "Counts each pair of faces once (forgets the 2).",
  USED_VOLUME: "Multiplies the three lengths (volume) for surface area.",
  FOUR_FACES_ONLY: "Counts four faces of a cube instead of six.",
  INCLUDED_TOP_BOTTOM: "Includes the floor and ceiling in the area of the walls.",
  ADDED_DIMENSIONS: "Adds the lengths instead of multiplying them.",
  SCALED_LINEARLY: "Thinks doubling the edges doubles the volume.",
  ONE_END_ONLY: "Counts one circular end of a closed cylinder.",
  ADDED_ENDS_TO_CURVED: "Adds the ends when only the curved surface is asked for.",
  USED_DIAMETER: "Uses the diameter in πr²h.",
  USED_CIRCUMFERENCE: "Uses 2πr instead of πr² for the base.",
  LITRE_CONVERSION_WRONG: "Uses the wrong conversion (1 m³ = 1000 L, 1000 cm³ = 1 L).",
  WRONG_OPERATION: "Multiplies when it should divide to find the missing length.",
}, [
  ["MN_RECT_AREA", "NUMBER", "easy", "EXPLORE", "A rectangle is 12 cm long and 7 cm wide. What is its area, in cm²?", "84", [], ["PERIMETER_FOR_AREA"], "12 * 7"],
  ["MN_TRIANGLE_AREA", "NUMBER", "easy", "EXPLORE", "A triangle has a base of 10 cm and a height of 6 cm. What is its area, in cm²?", "30", [], ["FORGOT_HALF"], "10 * 6 / 2"],
  ["MN_PARALLELOGRAM_AREA", "NUMBER", "medium", "EXPLORE", "A parallelogram has a base of 9 cm, slanted sides of 5 cm and a height of 4 cm. What is its area, in cm²?", "36", [], ["SLANT_AS_HEIGHT"], "9 * 4"],
  ["MN_CIRCLE", "NUMBER", "easy", "EXPLORE", "Take π = 22/7. What is the area of a circle of radius 7 cm, in cm²?", "154", [], ["AREA_CIRCUMFERENCE_SWAPPED"], "22/7 * 7^2"],
  ["MN_CIRCLE", "NUMBER", "medium", "EXPLORE", "Take π = 22/7. What is the circumference of a circle of diameter 14 cm, in cm?", "44", [], ["DIAMETER_AS_RADIUS"], "22/7 * 14"],
  ["MN_TRAPEZIUM", "NUMBER", "easy", "EXPLORE", "A trapezium has parallel sides of 8 cm and 12 cm, 5 cm apart. What is its area, in cm²?", "50", [], ["FORGOT_HALF", "ADDED_ALL_SIDES"], "(8 + 12) / 2 * 5"],
  ["MN_RHOMBUS", "NUMBER", "easy", "EXPLORE", "A rhombus has diagonals of 10 cm and 16 cm. What is its area, in cm²?", "80", [], ["FORGOT_HALF"], "10 * 16 / 2"],
  ["MN_CUBOID_SA", "NUMBER", "medium", "EXPLORE", "A closed box is 10 cm by 8 cm by 5 cm. What is its total surface area, in cm²?", "340", [], ["ONE_OF_EACH_FACE", "USED_VOLUME"], "2 * (10 * 8 + 8 * 5 + 10 * 5)"],
  ["MN_CUBE_SA", "NUMBER", "easy", "EXPLORE", "What is the total surface area of a cube with 6 cm edges, in cm²?", "216", [], ["FOUR_FACES_ONLY"], "6 * 6^2"],
  ["MN_VOLUME_CUBOID", "NUMBER", "easy", "EXPLORE", "What is the volume of a cuboid 6 cm by 4 cm by 3 cm, in cm³?", "72", [], ["ADDED_DIMENSIONS"], "6 * 4 * 3"],
  ["MN_VOLUME_CYLINDER", "NUMBER", "medium", "EXPLORE", "Take π = 22/7. What is the volume of a cylinder of radius 7 cm and height 10 cm, in cm³?", "1540", [], ["USED_DIAMETER", "USED_CIRCUMFERENCE"], "22/7 * 7^2 * 10"],
  ["MN_LATERAL", "NUMBER", "medium", "EXPLORE", "A room is 5 m long, 4 m wide and 3 m high. What is the area of its four walls, in m²?", "54", [], ["INCLUDED_TOP_BOTTOM"], "2 * (5 + 4) * 3"],
  ["MN_UNITS", "NUMBER", "easy", "EXPLORE", "How many litres does a tank of 1 m³ hold?", "1000", [], ["LITRE_CONVERSION_WRONG"]],

  ["MN_CYLINDER_SA", "NUMBER", "hard", "DIAGNOSE", "Take π = 22/7. What is the total surface area of a closed cylinder of radius 7 cm and height 3 cm, in cm²?", "440", [], ["ONE_END_ONLY", "DIAMETER_AS_RADIUS"], "2 * 22/7 * 7 * (7 + 3)"],
  ["MN_POLYGON_SPLIT", "NUMBER", "hard", "DIAGNOSE", "A field is a 20 m by 10 m rectangle with a right-angled triangle (base 10 m, height 6 m) joined to one 10 m side. What is the field's total area, in m²?", "230", ["MN_TRIANGLE_AREA"], ["PIECE_MISSED", "FORGOT_HALF"], "20 * 10 + 10 * 6 / 2"],
  ["MN_FIND_DIMENSION", "NUMBER", "medium", "DIAGNOSE", "A cuboid has a volume of 360 cm³, a length of 12 cm and a width of 5 cm. What is its height, in cm?", "6", [], ["WRONG_OPERATION"], "12 * 5 * x = 360"],
  ["MN_TRAPEZIUM", "NUMBER", "hard", "DIAGNOSE", "A trapezium has an area of 72 cm², a height of 8 cm and one parallel side of 7 cm. How long is the other parallel side, in cm?", "11", ["MN_FIND_DIMENSION"], ["FORGOT_HALF", "WRONG_OPERATION"], "(7 + x) / 2 * 8 = 72"],
  ["MN_UNITS", "NUMBER", "medium", "DIAGNOSE", "A tank is 2 m long, 1.5 m wide and 1 m deep. How many litres does it hold?", "3000", ["MN_VOLUME_CUBOID"], ["LITRE_CONVERSION_WRONG", "ADDED_DIMENSIONS"], "2 * 3/2 * 1 * 1000"],
  ["MN_VOLUME_CYLINDER", "NUMBER", "hard", "DIAGNOSE", "Take π = 22/7. A cylindrical tank has a diameter of 14 m and a depth of 5 m. What is its volume, in m³?", "770", [], ["USED_DIAMETER"], "22/7 * 7^2 * 5"],

  ["MN_CUBE_SA", "NUMBER", "hard", "CONFIRM", "A cube has a total surface area of 600 cm². What is its volume, in cm³?", "1000", ["MN_VOLUME_CUBOID"], ["FOUR_FACES_ONLY", "ADDED_DIMENSIONS"], "10^3"],
  ["MN_LATERAL", "NUMBER", "hard", "CONFIRM", "Painting the four walls of a hall 10 m long, 8 m wide and 4 m high costs ₹20 per m². What is the total cost, in ₹?", "2880", [], ["INCLUDED_TOP_BOTTOM"], "2 * (10 + 8) * 4 * 20"],
  ["MN_CYLINDER_SA", "NUMBER", "hard", "CONFIRM", "Take π = 22/7. A roller has a diameter of 84 cm and a length of 120 cm. What area does it cover in one full turn, in cm²?", "31680", [], ["DIAMETER_AS_RADIUS", "ADDED_ENDS_TO_CURVED"], "22/7 * 84 * 120"],
  ["MN_FIND_DIMENSION", "NUMBER", "hard", "CONFIRM", "Take π = 22/7. A cylinder has a volume of 1848 cm³ and a radius of 7 cm. What is its height, in cm?", "12", ["MN_VOLUME_CYLINDER"], ["WRONG_OPERATION", "USED_DIAMETER"], "22/7 * 7^2 * x = 1848"],
  ["MN_RHOMBUS", "NUMBER", "medium", "CONFIRM", "A rhombus has an area of 120 cm² and one diagonal of 24 cm. How long is the other diagonal, in cm?", "10", ["MN_FIND_DIMENSION"], ["FORGOT_HALF"], "24 * x / 2 = 120"],
  ["MN_VOLUME_CUBOID", "CHOICE", "medium", "CONFIRM", "Every edge of a cube is doubled. What happens to its volume?", ["It becomes 8 times as big", "It becomes 2 times as big", "It becomes 4 times as big", "It becomes 6 times as big"], [], ["SCALED_LINEARLY"]],
]);
