import { Injectable, Logger } from "@nestjs/common";
import {
  type CandidateAction,
  type ScoredCandidate,
  CANDIDATE_SCORE_RULES_V1,
} from "@cogna/shared";

/**
 * MVP 3.0 — Candidate Scorer Service
 * 
 * Implements candidate-score-rules-v1 heuristic scoring formula:
 * score = 0.30 × masteryGapTerm
 *       + 0.25 × retentionRiskTerm
 *       + 0.20 × misconceptionSeverity
 *       + 0.15 × explanationNeedTerm
 *       + 0.10 × explorationTerm
 */

export interface ScoringContext {
  studentId: string;
  sessionId: string;
  eventId: string;
  experimentId?: string;
  experimentArmId?: string;
  shadow?: boolean;
  
  // Current profile state for scoring
  masteryValue?: number;
  masteryThreshold?: number;
  retentionEstimate?: number;
  misconceptionConfidence?: number;
  explanationEffectiveness?: number;
  seenDifficulties?: number[]; // for exploration term
  targetConceptId?: string;
  targetDifficulty?: number;
}

@Injectable()
export class CandidateScorerService {
  private readonly logger = new Logger(CandidateScorerService.name);

  /**
   * Score a list of legal candidates and return them sorted by score (descending).
   * 
   * @param candidates - Legal candidates generated by decision engine
   * @param context - Student profile and session state for scoring
   * @returns Scored candidates sorted by score (highest first)
   */
  scoreAndRank(
    candidates: CandidateAction[],
    context: ScoringContext,
  ): ScoredCandidate[] {
    const scored = candidates.map((candidate) => {
      const score = this.computeScore(candidate, context);
      const features = this.extractFeatures(candidate, context);
      
      return {
        candidate,
        score,
        scoreVersion: CANDIDATE_SCORE_RULES_V1,
        features,
      };
    });

    // Sort by score descending, then by tie-break rules
    scored.sort((a, b) => {
      if (Math.abs(a.score - b.score) > 0.0001) {
        return b.score - a.score; // higher score first
      }
      // Tie-break: prefer control policy's default intent order
      // (for now, lexicographic by learningIntent + conceptId)
      const aKey = `${a.candidate.learningIntent}:${a.candidate.parameters.conceptId}`;
      const bKey = `${b.candidate.learningIntent}:${b.candidate.parameters.conceptId}`;
      return aKey.localeCompare(bKey);
    });

    return scored;
  }

  /**
   * Select the best candidate from scored list.
   * Returns the index of the selected candidate (0 = highest score).
   */
  selectBest(scoredCandidates: ScoredCandidate[]): number {
    // Always select the first (highest score) after sorting
    return 0;
  }

  private computeScore(
    candidate: CandidateAction,
    context: ScoringContext,
  ): number {
    const masteryGap = this.computeMasteryGapTerm(candidate, context);
    const retentionRisk = this.computeRetentionRiskTerm(candidate, context);
    const misconceptionSeverity = this.computeMisconceptionSeverityTerm(
      candidate,
      context,
    );
    const explanationNeed = this.computeExplanationNeedTerm(candidate, context);
    const exploration = this.computeExplorationTerm(candidate, context);

    const score =
      0.30 * masteryGap +
      0.25 * retentionRisk +
      0.20 * misconceptionSeverity +
      0.15 * explanationNeed +
      0.10 * exploration;

    return this.clamp(score, 0, 1);
  }

  private computeMasteryGapTerm(
    candidate: CandidateAction,
    context: ScoringContext,
  ): number {
    // Prefer concepts below threshold when practicing
    // masteryGapTerm = 1 - (masteryValue / masteryThreshold) when below threshold
    // masteryGapTerm = 0 when at or above threshold
    
    const { masteryValue, masteryThreshold = 0.75 } = context;
    
    // If candidate is not targeting the current concept, return 0
    if (
      context.targetConceptId &&
      candidate.parameters.conceptId !== context.targetConceptId
    ) {
      return 0;
    }

    if (masteryValue === undefined) {
      return 0.5; // neutral when mastery unknown
    }

    if (masteryValue >= masteryThreshold) {
      return 0; // no gap
    }

    return this.clamp(1 - masteryValue / masteryThreshold, 0, 1);
  }

  private computeRetentionRiskTerm(
    candidate: CandidateAction,
    context: ScoringContext,
  ): number {
    // 1 - retentionEstimate when due-ish
    // Higher when retention is low (forgetting risk)
    
    const { retentionEstimate } = context;
    
    // Only apply to retention-related intents
    if (
      candidate.learningIntent !== "RETENTION_REVIEW" &&
      candidate.learningIntent !== "EXECUTE_DUE_REVISION"
    ) {
      return 0;
    }

    if (retentionEstimate === undefined) {
      return 0.5; // neutral when unknown
    }

    return this.clamp(1 - retentionEstimate, 0, 1);
  }

  private computeMisconceptionSeverityTerm(
    candidate: CandidateAction,
    context: ScoringContext,
  ): number {
    // Active misconception confidence
    // Higher when misconception is more severe
    
    const { misconceptionConfidence = 0 } = context;
    
    // Only apply to misconception-targeting intents
    if (
      candidate.learningIntent !== "TARGET_MISCONCEPTION" &&
      candidate.learningIntent !== "REVIEW_PREREQUISITE"
    ) {
      return 0;
    }

    return this.clamp(misconceptionConfidence, 0, 1);
  }

  private computeExplanationNeedTerm(
    candidate: CandidateAction,
    context: ScoringContext,
  ): number {
    // Low explanationEffectiveness → prefer SHOW_EXPLANATION candidate if legal
    // Higher score when explanation is needed (low effectiveness)
    
    const { explanationEffectiveness } = context;
    
    // Only apply to explanation-providing actions
    if (
      candidate.uiAction !== "SHOW_EXPLANATION" &&
      candidate.uiAction !== "SHOW_HINT"
    ) {
      return 0;
    }

    if (explanationEffectiveness === undefined) {
      return 0.3; // mild preference when unknown
    }

    return this.clamp(1 - explanationEffectiveness, 0, 1);
  }

  private computeExplorationTerm(
    candidate: CandidateAction,
    context: ScoringContext,
  ): number {
    // Mild preference for unseen difficulty within ±1
    // Encourage coverage without random sampling
    
    const { seenDifficulties = [], targetDifficulty } = context;
    const candidateDifficulty = candidate.parameters.difficulty;

    if (candidateDifficulty === undefined || targetDifficulty === undefined) {
      return 0;
    }

    // Only explore within ±1 of current difficulty
    const diffDelta = Math.abs(candidateDifficulty - targetDifficulty);
    if (diffDelta > 1) {
      return 0;
    }

    // Prefer unseen difficulties
    if (!seenDifficulties.includes(candidateDifficulty)) {
      return 0.7; // mild exploration bonus
    }

    return 0.3; // seen before
  }

  private extractFeatures(
    candidate: CandidateAction,
    context: ScoringContext,
  ): Record<string, number | string | boolean> {
    return {
      uiAction: candidate.uiAction,
      learningIntent: candidate.learningIntent,
      conceptId: candidate.parameters.conceptId ?? "unknown",
      difficulty: candidate.parameters.difficulty ?? 0,
      masteryValue: context.masteryValue ?? 0,
      retentionEstimate: context.retentionEstimate ?? 0,
      misconceptionConfidence: context.misconceptionConfidence ?? 0,
      explanationEffectiveness: context.explanationEffectiveness ?? 0,
    };
  }

  private clamp(value: number, min: number, max: number): number {
    return Math.max(min, Math.min(max, value));
  }
}
