"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { getStoredLotusSessions, type StoredLotusSession } from "@/lib/lotus-demo-store";
import styles from "../teacher.module.css";

export default function LotusTeacherEvidencePage(){
  const sessionId=useSearchParams().get("session"); const [stored,setStored]=useState<StoredLotusSession|null>(null);
  useEffect(()=>{const all=getStoredLotusSessions();setStored(all.find(item=>item.session.sessionId===sessionId)??all[0]??null)},[sessionId]);
  if(!stored)return <section className={styles.emptyCard}><h2>No Lotus session found</h2><p>Launch the class session and complete a Lotus diagnostic first.</p></section>;
  const {session}=stored; const report=session.finalReport;
  return <><div className={styles.pageHeader}><div><div className={styles.dateLine}>Cogna Lotus audit · {session.status}</div><h1>{stored.studentName}</h1><p>{stored.enrollment?.className} · Roll {stored.enrollment?.rollNumber} · Session {session.sessionId.slice(0,8)}</p></div><Link className={styles.secondary} href="/teacher/today">← Back to Today</Link></div>
  <section className={styles.observationGrid}><div><span>Lotus conclusion</span><p>{report?.startingPoint??"Diagnostic still gathering evidence."}</p></div><div><span>Evidence status</span><p>{session.audits.at(-1)?.conclusion.evidenceState??"No answered evidence yet"}</p></div><div><span>Uncertainty preserved</span><p>{session.audits.at(-1)?.conclusion.uncertainty.join(" · ")||"No additional uncertainty recorded."}</p></div></section>
  <section className={styles.evidenceSection}><header><h2>Actual Lotus diagnostic evidence</h2><p>Questions were selected by Lotus. Mathematical answers were checked before AI interpretation.</p></header>{session.audits.map((audit,index)=><article className={styles.attempt} key={audit.question.id}><div className={styles.attemptTop}><div><div className={styles.attemptPrompt}>Q{index+1}. {audit.question.prompt}</div><div className={styles.attemptMeta}><span>{audit.question.phase}</span><span>{audit.question.subtopic}</span><span>{audit.verification?.status.replaceAll("_"," ")}</span><span>Confidence {audit.response?.confidence}%</span><span>{Math.round((audit.response?.responseTimeMs??0)/1000)}s</span></div></div><span className={`${styles.status} ${audit.verification?.status==="VERIFIED_CORRECT"?styles.ready:styles.bridge}`}>{audit.conclusion.evidenceState}</span></div><div className={styles.working}>{audit.response?.working||"No working submitted"}{audit.response?.answer?`\nFinal answer: ${audit.response.answer}`:""}</div><div className={styles.observationGrid}><div><span>Observed by primary</span><p>{audit.gpt.observations.join(" · ")}</p></div><div><span>Challenger check</span><p>{audit.challenger.conciseRationale}</p></div><div><span>Operational decision</span><p>{audit.conclusion.conclusion}</p></div></div></article>)}</section>
  {report&&<section className={styles.evidenceSection}><header><h2>Final learner starting point</h2><p>{report.outcome.replaceAll("_"," ")}</p></header><article className={styles.attempt}><div className={styles.attemptPrompt}>{report.startingPoint}</div><div className={styles.observationGrid}><div><span>Observed strengths</span><p>{report.observedStrengths.join(" · ")}</p></div><div><span>Still uncertain</span><p>{report.uncertainAreas.join(" · ")||"None recorded"}</p></div><div><span>Recommended next step</span><p>{report.recommendedNextStep}</p></div></div></article></section>}
  {stored.teaching&&<section className={styles.evidenceSection}><header><h2>Learning and independent verification</h2><p>Selected after Lotus completed the diagnostic.</p></header><article className={styles.attempt}><div className={styles.attemptPrompt}>{stored.teaching.moduleTitle}</div><div className={styles.attemptMeta}><span>{stored.teaching.hintUsed?"1 hint used":"No hints used"}</span><span>Guided answer: {stored.teaching.guidedAnswer}</span></div>{stored.exit?.map(item=><div className={styles.working} key={item.prompt}>{item.form.toUpperCase()} · {item.prompt}\n{item.working}\nAnswer: {item.answer} · {item.correct?"VERIFIED":"NOT VERIFIED"}</div>)}</article></section>}
  <section className={styles.emptyCard} style={{marginTop:"1rem"}}><div className={styles.dateLine}>Retention preview · not yet measured</div><h2>Immediate success is not a retention claim.</h2><p>A fresh delayed item should be scheduled in 3–7 days before the learner profile records retention.</p></section></>;
}
